jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: V9aNptAy+3rzm9niVF7mBsKCL/pOTtVy50WwAAMPKCa9ysR8lREBbcHo60jbQfhq1PIPjMCxfNwScY58B5SG6C1E4i9pRtngwckFMn/hy0o0VjXxchdw62neSMzzsK9pnwPrimQIyCxkA7vK8S0iDqTIeMCCa2GMo7VUO6G0uYY9GMCxaqihU0pC5J/4Xt9EYWPTk4R0Hhgiy1qmqbEmbeApp1BzsjoY7sU/Ay63TNWGEsUzM1q9jZ1ZnxdZXdEr3iPaWu5vvWL2oqVf4oFEgzVVD+ZDrDln3cqUAeDCiD5rgRae9jr3Z8RXLzbhZ+d4vpcEzFJLrgUojx/QUgtsrltOyDeHp4aYIcheKxaZMkDHAmVtpUYzyYajWiX65hoJmpBKPIDW/tuV8NVhEqJU9r6f0l2WN3wwUpzcLE4vcvpqLWqbDsfv7ye/2MV0rxMYUSC6lWeZZ7Fz70VENENaXRW/Gkk/5SEV2IwPaYOlZJHIpUfmg6KamLexw4HE9P7u6UWg3Hl7S8kbydNr7KzuaeXXUnqUzPKWMoh9W9foMTvccalgvhM14UPFKc232CMdIuKyQBlfP4gnNZGB3/MULOwUje6XaDUFt4KxV9m3+PXIuDICmqjVOKyRpQoEmmXwpi+3VBFXYLAdpeemmT7KtfeAB+srSD5ueP7/DfZ1buM=
    - stage: "Deploy"
      if: tag IS present
      script: python scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: SPkfzy0h/eTmbAucGptosuawpqfwQCAb353BcgxMGfYw5h6sa8av4OOgsSnAEQ0BEF0LXCyZmnI1Z26IxW6lpnj6gaQMHGEo7L4EA6rtsJIZwEID1jZ8ZfA9pi9YyKXoVF9XssFrLRdYZ6YKkkWRnJx8rPiCG5Pr7fk2zZOd8+BurKl0u5G0R2MU3uWWEMdJH7kTyunVl2Q7qH31iWWvIBTroHZlVcpZ40fLTO3L58bkAj4yH0aUfXlCtD4f4IIy4qcU+llsF0dHl4YI5dPYTQD4WTbAIzn6LbanSp9xPXdnz2VVpY8YnFKKE683vGK2CyIynYk+y2gf06V/5XJqP/sPwKPYh11oOSv8RigU2nKYqHlvKsucjcgapPO3b1IHx2VO/vie6ngIrzgNAvDYG4sN58eqJ0bpWZArXOrX4HClvCf4mZyykcaVAlhXn1JYJg+tNNI6bhx+f8hkKtHh6UgBPc2IyyaWNY1rjJ8HYSRR5Yn1I28sH+4zy/IjlLc1RT1+c2w+ymPlFFODKceAxMbI+8Ky8MpWqcMgwt3ThvpBCHq4GDX7ctmFcjf5+kPX0tixWcsSfAOApZBKxMTEeNswnQEycAVX8PsmhtWbAU9s7emNjDP53NLfqjhmdKoWqNqydmxJBjXBWu9qC/aEZRdYM/yjVQFu1alDh3XfElc=
        - secure: nFwSFljeApefg9JOLjF8OYcNFYitUIUorFOjPM4g/u/8CRpsuedH1j17s/ELOse72CqDrUK+hz+qRBJtUQSeVp2d43eRDwd4Ayq0p7ptiw3/FKz4ctRWsyi8Xrbf9Hebj6cMaKG1SOqu6rWxQPXzqcfjAkkGVlbRbdx12Cgr8UISMp5YlnG/M+8lWDs27lPDzg3NYlYfBEBhJNsnldumZ4v70npM2/pCbMlsqO02bPArsHKOtvmnROSqIRwM0VSl18oCeuujHEiCyCrCrcRUMPOOsWmZNABnsOog9dzGQ/clfWbZbMakObFFRNNnKKZvbVUrz0N5yqMKYBwP5x1jM05RaE8OknaBxSBDiJlFX3TywVwZ5lRxIIBY3Q0WgxKLLI8EV1xqgtN0KtNB+qtF5AifEDpeUEDUAenMt6GwdNRIM/Vn31VgcUmXZmMN56FoPHA7qjBtjiZvQzzHDNpy40GF/P0NfpKHwYFUr9DOGmYWitQI7e6Gm+7g8UMtFY90FCMlY4Az7MAs0XgsP//V/fDqtX6watuZhTpAYcjxw8AGwnAZaARVHUkchoToHm0UHdnHB1wSKtLerKMqkISoCYVn3m1yvQXuZ4Pqe0vYyb/frv1GJVsD1vtdc81rh2P/V4lJWqnF9i17K/tpYg8RmULm0iESH+KUZM4AK7ON0b8=
        - secure: To4IAH/pl/B0aVQqN10rhU5bOudg7pTnVWBjgnxVS6kIzbWf/SQR3vin/8YNQ2ysD8oh/4kB+P5PowLvCwVOStvIFuVAJ1p4eYm1UXtVmvrptxwZJrlMHHU/3NQAn6GJ8XV2qiWvvh0a483qOX4KiOtOjLXV6tyzFCH2bRz6TCyJY0cePRfJccJPcZxXltqKLbY+9BjIH3n8cjFr6EKLc+/LM54TDygCf28JbH8o6/pRn9SVyzFMV9u05G5q1RoODDl0dqrg46g7twEszSWKMkOmffOyQbiOf8qCCmd6bTmFZAZkdyQTZ/LJkg5SsMkxtszE01l61qJZ8JUhiK/R/nz54epL5c36zll35h9xga4mwV5UUjQWWtIOEke38MTl5uxUgu4VGCGxVp8SLhJSxSYdhbPRyECBPUzDkhhj2mTLBa5ZASzG8Yl6/6AyQuWO5yV6kYqr0NlDKEe8lwpXBXDCE0zgzqswYpjUT5Nmod6J2z4nM8LSeFOJ4GR6Vt1e17okn9phtW+b8DafxcqZok4dCZiFLZ52NoURoWl8xKxAM/H2D9mSkCt4r2UBcpS//RiP6NN0NcreozKS8sAFQqYh+Gkht6ixs+w2jsfiQtMQ3KuMCkX7paeEbVt6y1MxRMrox9IGXyfxbahppopl2WJxAgvQ8uTzr0GNB5hmi3A=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: SPkfzy0h/eTmbAucGptosuawpqfwQCAb353BcgxMGfYw5h6sa8av4OOgsSnAEQ0BEF0LXCyZmnI1Z26IxW6lpnj6gaQMHGEo7L4EA6rtsJIZwEID1jZ8ZfA9pi9YyKXoVF9XssFrLRdYZ6YKkkWRnJx8rPiCG5Pr7fk2zZOd8+BurKl0u5G0R2MU3uWWEMdJH7kTyunVl2Q7qH31iWWvIBTroHZlVcpZ40fLTO3L58bkAj4yH0aUfXlCtD4f4IIy4qcU+llsF0dHl4YI5dPYTQD4WTbAIzn6LbanSp9xPXdnz2VVpY8YnFKKE683vGK2CyIynYk+y2gf06V/5XJqP/sPwKPYh11oOSv8RigU2nKYqHlvKsucjcgapPO3b1IHx2VO/vie6ngIrzgNAvDYG4sN58eqJ0bpWZArXOrX4HClvCf4mZyykcaVAlhXn1JYJg+tNNI6bhx+f8hkKtHh6UgBPc2IyyaWNY1rjJ8HYSRR5Yn1I28sH+4zy/IjlLc1RT1+c2w+ymPlFFODKceAxMbI+8Ky8MpWqcMgwt3ThvpBCHq4GDX7ctmFcjf5+kPX0tixWcsSfAOApZBKxMTEeNswnQEycAVX8PsmhtWbAU9s7emNjDP53NLfqjhmdKoWqNqydmxJBjXBWu9qC/aEZRdYM/yjVQFu1alDh3XfElc=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
