jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: lh90wQQraIa05DvJNr8hmN8ZPXHTUmrQjHpdfzCYmJlkoAV83HtcthSJdw+lEmm5OSqudAqP0qXVbl7Ow40PEJT2WqrLzkGjgpSF5xeQFAl78Bl3ndQAPwSLY5T/Mdz7NfnhNqA4sH8zMoXQTIACzAfkRbopPDsPLfxPCCtHJVIBn+plEyZuCHLqlt0YSUyLeUBLjRpS+iED1aUAYiPn0p/aJAfIn4kBjd8cwsfsZ8vF8MHq64rfwknDZD7K+1JXhoOmoTyhjj9GLWKa9XfMtzY22msiMcoZYwUAOXql4DXxSj1v8E4R6guXnW+pKOWUfm3eNAbgHRVyj0mbd8JewlrKzp90eZBXMxlOrbM6dJGIIBLVBneqJ+ZEm30eEwPfgVvZBMeWPHpGCbedQ4FCgD0BUTuNF9++4ZM8TTQEOOSoI9x6fuMTzbo9q0fp9vLVh6Q65XQ2TLCc/K2wzzXoyaVeszExa3+8SCbEIA2D65eGgkqniQ1B7Mfh5OE8s3sYh5FrHDxfaTGpFcdtKDPkWEPl9g1JVuPR4PXJAAsEwitGp68kR2NUq/6AqWeDnOg8TKjoWlyof//YU6ak9Ev34mRiBachth0W38Zv0KCUELsIFcG+SqsUZ9k5MsNNFVbZiKB5HPzqd5nR2hnBcLZwPt/ru4TXZEMuLp0eFhFFWlY=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: CgX+jVQ/99RF1H7Tv2p8ahO0R1Nnw63Kx591hUGjIy1hxUyu2CdSrXFqJQXCGm0/GKbkNmOzcTCCNnrmdFgq7o8DVF5jfu096jqJPPwcYB3pMQ0Ig+/ulJ1S7Bg7SclNBOK8rdP7sGz6+GgLzyno64zBULrPfXrOgrJ/GaeOskg2AdXOJWttpRQ46127Rhpp5fgqdNU0F4kw/Y+8MLsMmDoR20OFxR7F81Bj3pdBOBJIwc9lD2umvYDCC7LZ60ASscCN8K5F9E+FZhqORC+AvaPeCrB1ZpUBJg9frqn4iiP7RjsDC8QrUu1gk82619x/zkM3NXMGp+vhdMEg7ZZj+LI/jnYw1Ye8LWfqm4c8pQTkAvEaii3SeFefw33fD4W40XNjrwowqARbHjsZR3fUBtaBGY1F4tzIEvBQv88feLzwV9Ho5XseOEM51cZ430BM9m4Ht4f7gmT2gs05XP1rMovRZOLID1AwG3AQivbrOvYM+a00uxlT8TgjDRh9E3yC6gX7NtPWnmDz/vy3/l1Z788xzJ1t1gDBPaXcCTTqtZfBER0uCA/Pt3AuRx23uVDrwzWpTR23dzvODLqGCE5bBB1q27VjSWw5rCZpodIbzlCXA02xGROhK9vjTzjZKjapR4tF54UtNQZaH072Kezn8hSLRE2DLKTnYNeeQO/1NIM=
        - secure: TwDaN4OcXeDHM8gbSV/HOoyRLSk2ryVp1sk2F4LaszF9uKAHzB9sonnz8Pd7NZHBaYLbxsm0i4Be+oG7x0cR45i2RyG+LNhq9sUE6ggHCTt6qnBObZeYl6Wd2pxgCTt0ZdCc/GP8KQXW6AjBrBg7oXCjTIQSCbwKrEr82L6+cA2s2mhUJ4VawUNuE4m02nPmNwMzLAI4gh8QaJcC1RxjdPvv5h8ZS/f/TksrfCrhna4hdwyddYYeEVZPSXK+Cw+N4zjiocZNFyv+Hz7oZUS7oASbp/7S8NQr57wX0I4zUQwqjMZcL7ur4l03iTsju7Kw42pkfm/0e7L10Jq4cGX0eqxiAZG8fVBJxfKQh/DAl48EUsKh4sVu7+1D98q0e64iZwl18+OSXPJMcf2D4ZXqUR3VIxOX9JJSl/tzsOWP4k2qDu6l7B8vDK8L0aYDHqmHFJTUE3zmLB4MQ2C0vdwxfs4FPocwP8PnOV8t7GrnQSiaCUMdpEpUD2YNLNSafcaC2x0HqAzilgDOmO3JASIalb1SbwWG9eVfEy8s7U/91wGQLYuoEc5qTYI+AZTynrQznUYY0/3AroKW2q8g1mEWbcAAybgA0LqPSrueLqIYWrI7BnQdSBCIJwQylSUuQBhDRHdR7zGG9Pj/SaLdN26r1NZFARvPnuTgH9vfXgNBTi4=
        - secure: TCnhZzpDuce8cYTBITnup13phHvjsRHvhVKrKA8pReHiLDJPiJo2NsY8Hs/5zOm+V1TS8cmrfkrjCPZz4DSV7HKxcnooTWAB5qmuhUGZWZpHjvl9nmtlftTynEvSMpDCT2pR9jetk/kDPmp9AD82EXNzD+4vbUlnoxhzFUUX+P+w9ODRBWrDYMmtxGlEpDKtB+Vtz7fgSXWALrosp1hOFpND0+sJqmfNvuh1hb6Zzb/ltPiAupNf/8K+q2hh1fPkeCT7AgHEDc8uZE//4HvsUfie5myNlh+bTPYtCTZ20wUTy8LA921B2xetp35gwSUPHBnH28Zn2sFu2T4hSQM6arIZOAmlRN5Hv9AXtm3ceqacyPHyIzXzTWta2rSfDXdq3b3WQTlrQWAhzEUD7uhrEgkxktNM3SB366WoyB8HPHmnoc1G+BXT1p1uATWJ+Q4cERPL8z7laTv5bqonVu/c2pBnyQNSx7waewrn3IZprGvoTNSHDYWvt4yboJYIrzDwbkhsPl6xu/H18CLEqN7YXt1C9D1Jyyetl0QwcXoFcxwUsKU65Tf+dERf1MLqe5/aMFVnh02E2egkcWBaTy9A/WQ8XEtgD1X4V2iPpPhWLPr63tZ6wpNBRhycC6MdA/QfGp5fcZrIPCg9LzWiCbHpuztm2Nil9coKmpCnSS8gKss=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: vw8SsmmlAVmmvNSqI7MuLLBUUWW3VhnFDjDAdDM6c1Gkza3fJiq5cHlRNjVH7qceAdLwPgKKlMi0Ocq2w/LKoAXOZCvm1uSEPB0BK9bZBufHAFP+aWDcnVM/R89I6ofURCYIwDek6X5RTTccvhReMWxDKKFgoaXu/m1Mw5fQqqlTRRH2CzPYkGdhqvNHg4/fEJMqVb5eiFML4rYO09xYsqsAYkbSq7Xx339HXJNGLAnENQGdUYGMFsvbvTTevHe4MGFT8paysIEs5y9B1hGHz3ZxGUo36iCOg7W1zFTW7ZIFlA2bQ3hSmxwQNQJgEK1LINl0PbivZELSwk73IIdqqg5RdyooKX0datW5Wpa1NCe2eeB5kyVaTdOlzkIy2z4uCuO7W4z0x0b0AjEGg3X9dZBL6nF3ICmQ38+juhP8yegAm7oWskoxzDcOc7m7Xe2xQNoj35m9HzqzcfF4YBJ1ZCGmTHF7l8c9wPoTjX5i+76q6M9wyhqHPqVXt5cUwu6OJVCT5sTQgTnEPcARUQtxJc9KyeS9zwWdHRZYSMvmt76YWVsJOyMSXmKiib3gBEA0/Xhy688tfQS6U2pFUFfQj/6pxI7j3VG6lIHQf7O4ywWAPxynDOQwSVZokBmhdQ3hZC/pkYVrBY5pPZXLMiSSAtv/Azki+MMpQJoR7OsWlsA=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always