jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: ke1zpxTOiYBkCZFtUV364VO55EJXYdUIMqCboZgR8Ss5GHSsF226CGvbleLXsigiY4eQvQ/VvCbiuYuJoe37vwGnVvhMiWK8tSpHx+tVvXquG7WGFodneA12MDLDH+PGnytVWAHJth18viFn33fJZCubbB9xEpfoXAUy8yoS1XN6wLM+RL8JIZBCOZDAiOEdNyZhkmwkxupqct3T6GL/iv7ydlhH2Lbwu/SmnjOaOQrOursZZtdGnIC2g9zWc4hMeWl1zIEAayD8eAazKJG3djkadb4hYRJXOdjAs/YqyP3ZAPqkbbTvqSLc1GBEz7ZYG/ZSdb+dS/CzfKbJ7+tRp1W7l/eGUnPcUbRZP1t0/KUXWwhPrea2aQt7JummPB/vWM51WveHWA2ci4ZEFiFbgkNv1PLVY39I95PeFrAdR2eDtfLY78C+s3/coaFvBQRybyXRG8Lzf/1+0TydcQf18fK+hVQfw457FRCiSpLqOL4Socmf+FB4j2s+6x63WFl7xjk4MXjhUgu2GQeb1RTL7K8Tyu93j7r9z2TxW9MsBOvOEIujrycUlDx37vAi+cd1ywxYV3N80UCafSr4czz4u1VpVFr1EzXVAkXVlzFvgbnAw8yjX7WdXpA4/mPekqXBX/CuSKE/sn07yvkbgdYESGSbvNLdXGEnxvGFSV5Nf48=
        - secure: DzENnrjKRZ10Ehf3m7ZmMbOxYNmi9m1/c0/78RWiSJ2pSh9DUS5Y058Q46KHiBNYDcECZMyz0adecMByNAu8XJobkiM6lquJbB6NkxiNgWqniuc6Y3Z/BbSoY6K3aDrSHV96+FMV51LVqv3nWzMg+NwAuZuyNMz8x9TGmKdptBN7xDrMHRJY2k4oMCd34RGWBThyeBGe1OiA+7/k6/HGdHiJUrmLPwIG/5jJ8lABKt9Moid9QegVBgfyivxWDIsVZEwGZM12qLmZ+oxhh0DATNKtF1I5b90kpMB8gvc6NN4o21dbNwFv0u234TogFgbwE9xp0ejVwTAMCGMJVHYFwAO0on4ryT9H4rorFg3hdzRALKdZxUdVEORdnNN4lWNZ1iZbhrQtQa2+pNMsfYxV3CAW3bSiAryKE6rXNsJR2lsmY4ENmfdSwowSmqIUAdKO3hXfbiEXeaYS2f//pQHP/xMxmFHcl5lAuQ+8xRaAwKJeA0MhLXYvoeOv050uEa2sZJZwVW+KPWFnTlmMiq2tBQ587cyMBy/jNPRVJcEbksZog26/LRSKdHqwjxHy5Jdu4HpMRYza45cJsmV7VldR7tHGrNqKn5U1KArXzONxM2QN0dim1P3TD5R/Wa0RHnhfJlnIwB5KBWZcDwtKFUm9hhzbE+v6ErEW0OJD0Q9pjGw=
        - secure: S9N0JGaI4G7MxuWCX/z+dFNjXelZC0czPeM6uKZOQJ5FK0qgtyfah2BG1FEp23peQ3zXuDsiTWo9kk+tZsuFSGqnEk4TV3oE/WpZHEa5aMLk52pBh8BzedV5xDPeajgJ/0neCLpTfr5tbZ3d2K1hT5ce0HDgWzR+rBAKNEcARo8KuKLWvvyqfypH6uIXqGqmG+r4HuonF2ZKp5/KgwDAbdZtHL4J8lj0QvkyvXWqh1mFsCUSBQuqom//s1i38BGJdBhzOR1/BgYl2SoOU2OCbT6BP6oTe1J6t14Zc4ddoWkvwWGlkxd/VBrWNTNgdIcsS6WDXfbfnxgmJvDPA+c3AnNxM9AomNA6R3Cq9nPsv/9+6CXBh5z+RsuWgh6fbJd4YxRO/qvJgqF8F6sb8GU+gryWEIpOYqQFSCVtoilSJsSxZSr77HKi/klBbwiz3fbm1ZhD26SUqJ2kYNbbnN6Yw+ozxBA550qONw/lqSIz2ZH6VqysktEnBFX3IIA0t/7ec0oY7bUiYSq4ox5izaKopS2Fyyo4s1poKezpSweGmpltvkfdswoHOuIv/HQE+xYMQTMAcaGuBuJDB2qhaMm0YEQ7vJ6q6m3AsKRM/n2tQ6kD/7/tq9/IvJHRZrDAxcKCFL1LsfbiGiIiVeadTaUkCZ0llgaxlJn9v7zlPpmZsoE=
        - secure: nzIlYv7pleQ3MeM+2NmyXmYE65Ue1RFfs5XOL7jGvIn+j1uAIg5WnecZ29TLl+QDYMzNjI9RYrUpPdFFfXNHZ4NZroZxRrVMtdlDX79uxqjg5tYp1M5ojdEJosuP5qpc2Vbz38ZtTD6gS8Boz+d4cit+oWJewLQBBejr700z7PDSutuDdNGUbnSqAjOTAYrmB9pn1HtLngAcs2BI0lLut+z7Wb8gH6yQ0HBPLvAqlMcuZbnsS126DWUVuTrGvc7i3nc+hOlIV9ha2uNJMLEBq5jhBbHyws7Hd4zOotQ+9I261dBlxKtQIUCwdBGa956bvH9VMMmjicvn4n/XjVAu/G6PFCb3KT04K7NyzTFkGcmyTJ6ZKZydVE8FKod+q4QEVgYRJZqG332di2XbtEoqpuFGiS3g1ZeAFggf4wOPHFDudLSZLOlasdPf5ICPvXi/9abnEq5JlJWmAW8ESyg+mFrTx7dmJ/DMjpXNnb+k03rbm3pZrwTRDYe95UtNKEj2mS0bt/f9M+vY6azsrPUYokr5QdgMkUghqP9/o0AcpfPftsUQ3iVN07QK5nH8QCwq2fmtFs4+ZbYUBiLObXD1NiitbvNyKJIcVz4GO7S7xyLZk4UK14C70cuPI+V88QO3Z3gxH77Tez2tq5PQkBNzLueSB3tFCQiEbtcduDr1dk0=
        - secure: EOYP9REvAAoWKfWa/pzgvbND/cWgRziNkMZa7aHDrNo6cNLFcd944nzemKxGtXbHOVmhIrQdXzYZSoakugylmpeljzZLAzhA70lNzpjBW7FxwT3BM0IfoDpXdp7jmcUi88/2oWaOEhhboOtVkWKbb8UIspqVZTK6L05mLbvGOsnWzxBxI7ZGiuN5qCI2phPbOLYvlyV+tVJn6zBFbNKUQRSfgQ3GfxnFUXjSM9TbgRWJnJP20g5+UMs4+fG34VJxKuYYtMtrslw1rhLewb0ob+zt2VTXbdxltWdlVhKi2WuOqRki3oTjVF8MwoSVP8QDBYWQss/mU6Ds3wAjJQTs1bwfQIwILf+gSplOBS7CsZVbE6rmmXZPL9qu8exLfslUn2JFAEeVG9OSUmKg0MH0zzmq3vo7j9ON+HmINqPrUzgwZkTyBfWOo5uzqc1KslqiZHfBiDDHvb4teKDxOns2c8FPqmKd1Ls6SHma8HwSZtZOXAbnEtDCBOihLeEQ6Z/eMGSplfuo/6PQx3PVq/+mlD70Zlww/Lr32DTCir68Sr++0292CMJTOFz23c6pUZe2RDsT9qNGTw5JOfhlzDOGaoDXlpvvIcuz3hueGhVtthnKGyeYFKHrcL1xi6sTOgZMKdYM7MfmY2fjZTxwuzKHtIMaX9mzigRjY3xXXt34DVw=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: M75KsPFRpZu6J9NuyKeAZ5iCe/GZzcnHXrBIn21VCkteCaE8urTTERb9GGBIteGyW/WE2l2M41fwmZMPc8zAkFzqdB0e+V63EuDbvlqHlKhdbx7hT26C/UZAcN6t+hKc6oIKZRHz0zm6U+AoYNpiSoKBwnvRxJ76P6zx86subVf8lAj+4gBLK+u6tFm3q1R0/29v9uWXL/OwGlbqXj4qRI5HuKuMbpcS5CP2Re4FpC1C/zZoVcbtcVYhZvhwNsa4B+H8QJOf09+GPpvs1F5ReufQEjfqidKIxSFC91phGbtsVLmvkPSKZEsVA46Z7JLEGly30Y/I/rLtpwtc2/EgqFHh3/PfTSCXHWbzQ3ycupZ00F6fFlAHLLr6evJhK1A9avAExKlQTmiyrzdPHQI3UBwGUUgGqoFterWdxtNdgEivIipIp6ocyh3Iy/hOC6NvkblJpIVQmaZ+KdeQnctVVMKZ5/WuVjFI6IVH07zleTk5wFdYUgxG/wpt0TOB4lZS3szwT2Om63T/CSMb4gxQVw1WoaLohZovGvFM0mkfere7Cd1YlMCm3Pvd3Ii9pm/xbfHe7Sg4FwOqCvvmJbavw0I+IgadYT7Aru9fuBV1YlEbMH194CAvX9OM2m3QN9GrfHf59mq90XxxoW5JExq4ljmaysYWL40fjQ3kJkFYauY=
        - secure: JR4gA1GorXNzeOjjZaSqxyVRjtq2Q0GQ0L7MLG8+CyIZH3FIaQgpqFeHSmpxhG4S5l96Y2xhDVYNufXGWD/yyZ1POcByVRqGD5baRo7UqzpG0iXGmP6NSFPdQJczMlM32fuGj8Ilp9uespvaM+IZUWELexw6mgUBlSOUbbuHh0ql7ufiSSr9tSC01b/b0oC+++ylNZwYZw88VO3I7EV0bFjAZbW/+9Dk4CByBnECDJtzdNugZB1MvmgUMYMDNJDUzFwLtTAfUfmGmdiSU06/uYJi3IJPKoz2icgGkdxSTTsS0GLhEraK7ofb0V1TeaMUxLZyIfTReQM4ykLCKtVbarn5llU8hRNJeDBIfU7KhHMWny+ezCZ2yrhdQgW5extUwfROeRUs6+Ew6bOI7LNOKMoiwTtbHnPZHjtFfq3pVDMQuQnGi1nr2/42ol3vmwXltRmKmUTw1uJHxRROAh4lomX/PmqdlJd3tFlzuZt4jgIrahL0kYOAtdqTOu4kqs6LXCIlLg7Nqtfysmy6AXu9RSQNUbeP5VAWNNdYAUcTBJgXYrh3Lf3dLZGn6xNgy/noyGYrcl/gCzN0xyRRD7bHo5H+W0hJOocEUimCxXfeQDUeUK4+2dexcWWt0fiTWahM6aI2qtUEqttKslfrdcQG8fFJTVAY/E9RRpka9Vzn5FI=
        - secure: hC0kZCAZoultM/wCPvZlEqzZtYZM/SrUXPbsMYWbKqukvAf4iyxXcn8ZiTPt2gyxx1eoAUXoNAfnLU4bGBYu70Df9Pz1WMi4yu3dHurHeLj9DbmnCWGuq3N16QxU7EsRiHd1roFSH3kfsQa/tVZFNNaytoqPe2iKYfb2UUwX7N7kuvA+LQK48NPa/YcKY9QHL6DsUQlLZB69QgCvlP/GHc1/6Eql0NS0UGUtzFddIqeN3GnX13IWhIWIRo6mEvudZuMiI/11FmbZ7B23yw+HDjuQ0xbr9DWnjhdoU4Ag0afe63PXnRGjg1X1D5jGZ/O8zOpNPdrE7LSgLpawxweYiPOiCdFMI3JEouXIOeSa0IuoXAVqKKtr4wsa4fN5IvOY/+LCUVyj1rtt+sSubbR4m9NBH5wF+VobR1a5DMOeLGpc0Z3fHpZiZ3TAjUJjxDDF5+z8lS6vkHJPqMYS+1gavO1WZMZvGhpGgDnf9XbwsAubd6HWxnNY/AeM7OpWWnh90wm6Qz55xC7YweBri24sN0B7R8ePNFv+KTSJLr2vkxw1Nd3+4w+FsrRM3Xod24L1BWzHK63qXOJYZqJmbSYNq3H4gtpry8TlAHSuW/vKji+jkk/KnNABC452r3hHzu6n1h9TGFsS7SuGizB7/EKuAYnhe79Zqr6RlCUWXsFUMoc=
        - secure: FQxPcGG0bAmuMuLLjz6txorN+ILnFp0egZ3Heo+5LioTjTZWh5YOrnJw+agTuUlsicZZvw3W+7yFLQmXKzN4sPmEFKRAzeRcvY8ZqOjWw+E6Iwua1zk3QjStTCG/d7HOJuJbuVm9S+WmqWL2C1pbkK64VcS4GK+OfpUQB+r1S8U45wSuvN1CKN57/VMc7i677QSMw5TAwARLv/wCMbngjpMkAlGD7i2YxBSFbGpQTW3jHnRW1UFLW1LQaVDYBtVx3UIKS/F2pWlLRLoqqOj1FjVrL5EOYPVtjzkKKtEg44V/9Im4oz4J+dwvE+jY/oLZPtt12Z4xtWygfeEYf/udrY4KXJoVOA62RD+fSHroF695LBno01vq60NpPeJ6LT3KOlNg42ef0BZcLHVQx35nfL2qmOIf4HNBhmsID2VOtmMo/7IdoXxfeeBKy9DUpIJ/GvMPeEXsw23Ub1lvlJwiar4nzv3vy1HfkCfig9hmpEjyAd+7dSDcfnhf34nNI5zAum6gJ+BIgeS0MdILcNCCS3lKnS3HLVHMS3W6CpF98qEdTpDZtRqoOkJkbxudwp69WqEjBVfzesFzbdvVevJW+SvYf9zC+Ta5h9lfLo7rEkn8Co/sxAdOF8eiXQLMtmb1MjJ5kbyyofqF7J5pXTi3KM4nd7mfxQVNIjIF+/NfGb8=
        - secure: c+JwVEzUN4PjASyLCm9XfVhAW69oRf7g6XJvnPR+i4sgsBT/bpLwaDFW8GyITgWV3LL3KDmmI0kDBgRG1UvEvKLlE0bNAR+S8M5WFc7n13I4md0ZMKJ2ShvlOG/aI80pX8FuVxQ1v+2YjGrN4J6VBGg31Ft2ko/CmZtqmPoL6kcHRhCyi1RAh5e1yASn/jUl7XTmXScPheMZqW3f/xycZy0tOomMQ4763tOmqWsLa0sv64nMbUGfnpYt4VVpewrr5aghrDijFdlxoP12rsYR5TaYe7u1EUTHoFxbrcFr4GjPfxqou5t4GPLEHXkZlNeidK/DdK4agDmYAe+hYIco6AuaTn5lpETer+g4TZ1E5eY8CD8pczzY2rvo/TSHExog2+w2x151QW5k8SJSew9BTDZTC2Sp+eI59NkquGUKXXnzmATq91w8sEnfPh8wfL3jAEmfUdCkRpALTNTHpbV55kQc6iaib/jKs/A6Ziuuhzdj7BgkuItElfbpNVfp72MYHckT0Y1Z8QRw31Nc/f02818TJyZXj2pPxxUFaENnULvpmpf7SWdJzKzTakP/MkXpNTmvKvI6wjpZF0n7zHxGLbBmAoPbv7m/ZfVss6nNe4TCd8RGN4DolTHlKSzFBVEHSQLwriLyzy+/M9Ny1eixwq6wtl55wpFK6ls5Q5k9oyw=
install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- python .multipackage/scripts/test_by_name.py multipackage
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: QUYe9U5Qd3UM0o4uxmbruTkS8FRKvyR/djAk3WeR4QUpaD/Lv+VJO+OeDCoPRv+J8zWnttAw8BYqwJ53r9XqtM71bXx5z/hLKkitTt4f4p+9N58xcXv0X7c1tQSQChKL9fW8cebkFLg9VJUsNwR4Kk9drjtaXY239EWYXQv+ik2Fo/11KzfAiKZiWVMz/CAdx2foeVOW0lv/KO2kqLSmXrWKIFzo2w2+fDqR4/f0owH2AAWvuYtuIrdkRxszvp0ZTNC7DL5UY+rTCCHffCeIrwDnYVg9lY2mfepUc8bO4mWNFlCXU+IpnBItnmFEThmkdHKvMmRlC8t7eTMlCB/69YGccYZftCPbormcHS0aGrylQq3d99M8WDZduW2NsUwkYob1DSsk6fDeb1jaWCs8X1cxKqQmZW8njlBElb9/dBiuiJ1/cZ9hGa4tM4nrFzSHnPQCT9+N3C3EI/pNJ4Q5oCTaEo5ewccKwb1gUuTlMxHDe/V/biKGveT8DeOcxC262BUyWbQkYuAldlaagRfcouTIZ2lHtO9jPgdg5UJYyS4sUoTdQkJQGbPR/4aGa1XI4WSi3SwllKRDBvXEqoPeLCqWYwJz26nHAfGAim+r+VEZM1bM88KR1tnFcwTqijjQz6DanJnbgIQ12mXuzEQ+2V2GWrfUwvllA3Ed1JABcXw=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always