jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: TNdFf4/8tUvpJn48fSZjCF2kAda0m/r6Zw/rgs0Loo6eZoaFSz321+D54PPTbO00xjldC0aNO+sv6ZD0d2tkomAGdJaDF1u24ydJeSbYowjX2N4FE2E5GHE/vdyfBx7gluK7mzbQhAHzSRZ8GF6mtfLj9VtHyo5ZVrhwvsgXQX8API2TV0vINB4PlbaA2HzMRhEzBcuCZOSyOf497VU++IPOWcsycS+0HMypczoWdXIDib7bdGq80Et97ylDP+SFuuBPaxid5krmlfsC2xgFxTSYseIPE05ZA6GAsChdsub1onRiSiXe1lUVj/bxXb7/c1o3EfNAsJFOrD0f+WbsLoVXqgC7VXLB/KAVJq8TS4Zwz7zpURHX0sFkB9CsEr6j7HiDO6Nu0v1dQ1Z/dWLIReEzYJr5YpXZCrkfLOf1CZXhvJaTkdBRM9Y2ggi663xl+UYND454JWVkextgZWCAtqv7E/9H3GwR1b7MgtL9tfzz5c7OEX+C+EMHuo0uvokzX+Osw1DVp92Ng0yhBiqBJWsJYE5xusUapsVjuYU1mDBGzEswaVLf2PZo0DT00GgNf9e8kcACEplFEhHNmvaOPRns/osBlBD+ykwpl5OgsUfw8bIxdwPbQUatdbjSGY7M25RSeT9RBvns53mp7aVPU6wghE6iLF09S/LqcGsjbg0=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: l0x2nf5C0phf6ChSYlo+TpWs5W3H3d0NSpWjISZZFsA1E1FVXgVZkbd7RPPc56PMIDmacI6V9FO8+Qa3QInio3DJAxo2qL3EXqbsiJRUfN26x02ne2J70Uq7w47fFZLxzididnnUxl/L5aSWzOMFcN/DIlcVoUnzcXgsacOxg2hH52zddjPgclBrrGIf4iG/xPjJwVMctnH4SW3d5OfOTBTy0z/5O8Ic+MY/0qqxtPDrFnFTR2o5IrbLHssuAl0iuorRCsQ4y38UZBryqaoFUYwc9ky3DsGrA2QiN9K88hMmd8eET0I2C80tjvyxF+wy2rjnBrdRHhccidj0PxeSJx3vknSgMXmSRUhUKLMCFod4Lt/FmwHgHs06THoLiDGpFamumtYNKLLEgOBQCYAzEcGc8dTatxdDiUsX3H8H7goqFgFwMHHXklLoDLeo9b8iieOXli7HxPbqsA4oIQW/jCpH3PZF26Y5y927Mb+X8YQGMMeEyArW4/uu+rKWabbejuF+UZVTqw7n+HHamPSbd7WJ03TizZjeiZbGprfhAzmxJAhAEtheajz7PC4pZmmEYf186WFlxKCic6hnWVaS92Ardrre69zV5I6mg7CRLXNeL6QCH8oUo5g1/OLoZDY3BuoJYEVu+o62yh2eTX6IwLhO2fPkbsz1RVpFCkpgwEg=
        - secure: eHWq531YdWM9ckxAWwUdnlZ2zG8pKqM1yx6FW13BX7wRk89AopPd64K/ASekOcI8k2S3ORbclXw4JFiAIZ/Q0iUZZCrfIzZayTj8TTZ2fUnj9DGwufyZxo2iIkbV9KoZ/31tDaPdNXPvk9U/bZLjb1plL9vk8n0cBpOn6ReDk3DQWxRr+AC8tG1wZJ0Qbhljn9RwzyU/NN2r64RcFLtyaDfRE4j7DMwafbq5J43dNy29+cnZm5IIq/zT0xY8e49wcmXoOxnHl3j434EZgDc1hgqj6KO/EHarmTy/jxjD/JQJ4hLpouefy5p6cyhEilepqmBac/d41KaT6aXsVCiFWhB0x/nJXo1lFXa2A5z5yskKEbaRRqkVbpwmjXJlQAeFC0lvSruTKmJgr3vrCUBfsbMEnDD+2voELkx72xdpWmM5/Sxdqo10eTH9eecXLFJZb1zPyuv5dtC2nQHFCbv2/Quxsrhh4+V3RmfAaWyTfUrUSMSS0p6hFCg5+0ig1a/jmQLd32R95eFiEP6g5Fd6mWfGl4Ovfn7jQc7U6mivXlbelvs+74qt5LPLJO3q9lwqFpsHhMhCqWMwuc/awZcqcaa3+tOTpooGKaQ6t0fNC8RiZQaOKy5GbfxSlp/UT+R5W+b3NULn9UZ8LIIduGRlM61Ex626sQ+Kyc22p7Sxnqk=
        - secure: CfNFSqdXdCNputAIxxhBF2NW67B3gUApMrVJVfuhtvC0FgtWuDDL6VbU4myCHp8zigfh+IK/M6IlX2LPR7VkvBVop0mYRz5Vf0hmWYKWY+VuJj5xLbjLPL0RvMCecomP3u1TnodYMlphgVokWwX562yO4NVAe9w5hxgwuTeRQE1Jl0IuXysL+D98zpjLauquHhozY8VpOoXStEWPMO5RjsK91an8X//1AQLUyf1+7U6/vR/pLmg/KgMU5bK91Fov/FxaTwjYRoLVXa6mI50H870h7O+6IWMNY953r+v95C3w4QK08fyEIpwvX4BMiK5ilfMjTqLvs2vn8CulDQRL4NlHwDKf20Uif5MA+0jJed6FAfiWL3MVreoTpw1S52l0EYkoMeZx1tNY0S68KCoLJwEPz/Yu9jtAzdLHmTCkQ75v+QWdea2POeomPVGvcsTF0bvr57ewGt6U7nFnzl52QNPnT0jnSp9Xc9J+xy8tZ5pNTklBfYbBOIlnnlsH8zxyvBBz5R9MGhcnxr46QlUXdmVMaquY8jIHLqlRTindk2SnUpQ65DKf4IwJRjUuDhgdLiL6WHFzO6IltMyEmdWv1FceeFx2g9TG/p1bBZBBImvbikHsB00k3QlmhNz8mwpYr4z0EWgv/14FgwwGtIdSVCuCk4bHvEj8kLiM84iFFqU=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: sT8Ru2r3VOog5oUBLNsf8e5zpAoPr2w2F13iUSPoonHSswmyDcIZZ0LO2xzw9FimPiBpCX7FYPOjOkj8NcAvGBZvUg5lAMz1ML4woaXJa7LGctj27EVxXVcvZ5cXSfaH0uXN0E/Eaw6jHeWpPaiDlsnlKeE8HCMd5Dt65Py5F7QHA5QHN3j65eQSBS4QdbrwyQJNS4jsAXKH9LfzgQ4tt312IB4cMyoSIfZ8z37AUF6yq5F1k7iBVAmfg017Vvx40BKgrD0a8gJmFpF19bSbD0Fff/CnrtQN90eu3c1rgAtmeiFkuq+ZTMqF2pINEwfM9ZB2kUuGMR2mCCDhfIIKmAf94Yb4EHgsqIv3cRpjA1D9pbHtA7ibPiDX8gibmWrHaIusDj7WY6vHvEY1XS+XBTwZBlUW14n99Sj5srkkNJZrixwEALI5oH939l+Yszj8PzgNKiSD+CGVXJC2yf9WM3WHrWMvaxdwfnQUL4S8n1czNSK0UEpWkMwIJfXOwYv8exzYvkkGY7hLWBSEg8e1wOJqatKJD3/YskvQLh+6FlloGs8MNS7QyT2J/UDpECsbiIZHYhxFaTPXwizSKI9WsIbop/p7/oMypGoYq7RSwhmsl7veB6cousVZCjiJQSPc00XFUnsJjATdOx/tBeXXCeQk9owb9D1Kv3EPWSZ87UM=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
