jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: G4r1L0CpswbDTaM7KyJxueJHpdiHiXnrBSMjz8btxkThRZUgPoGRyfWdaaZM5zDC1QYU2joUAZjl47LalV+Hm1yxFz5sQpjIu25F59ocUm+ZlkQcZ2SVlLCUbsTnlGG4XQ3+QewVBbwQ0pdlJeY0VzweIZkShZHnk6CM9hWP0TnxNr7rF/L8qGfi1QiUD4MZODmYyNEfFAUMPta56+Bv1GS+1SO+eXBTmelc3iN87oWsdPzCJ50HDMHD0/Xir9YwwWNt6h2AIDTqZYrnsNcqBo8uTb2BiOL+Aj8kRToF9peQ8Kn36CcrJbxmymekkif3+Ol2cP13/ZoxldlXZkknM9GeBhnwTjWb1+Rp680oU30h6eR33cnUwXHLhPC79AenK0RKjqkCQZMveODA++PsZVLvg7LYaqOTWJE0sCj8vvJjYsGM0FCvPp27FYVI3lbEe6zKD3wACHsWMHb+MdtHsfn/i9hqe7bSXcQYBCcAsmbDeEuC++fJb85dcrpWrUCo8Pqw+NCW9QrbB6pIij9y9egGdzmtE/PkQUvY8u7rzuRwTILV94fd/Qq5XZseG21MEfx941+dRWoqMJIdiubympQNwApTn2w36bynC+QwOIBmn6Wfj8Yj0wezCeOOfbDJlJrHQ1yxxQ4oULRsTlLoU6NI0pRMLSA+i4QWi+DgHis=
    - if: branch = master AND tag IS present
      script: python scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: GoySwr8NA2ee00TT7ARUTVmLUgFkLzlWRFWVOGqCMCcPGv892bJdQueipYZQ1PfKB2ByFxXWkWqRRekASoBcuH2zVFBBgqXU7+2BzCMcpoiW1+M2N9iL69hMsR1BDPnOiJ9+pepYb2Dv3BLHRkFmfMRod4yXpQbYIaQLVx1EXbSYBUNvC2LdO9GaKhbp4ZCFHEBks2Gb12sBzklnYU2xcIQs5DZeFBo3ic7LQi2dDFuXPY9wEP2q5PF/SP0R0NQ7DFe9RzQKcBg2BYRsr/aBN9CG2boCyTDUuLSMs4Ei8vXA6iWecfYIVj6BHF3XMkdfc6vofILwb5PYbZVpKYzbkCUWPSFrzzvDagcOF9uBhVX+/9/ouBpXYySk0YCkyjNpmrzbhyqGAhX99vDUgVXTBZ5LOgqybFHUXmiXM7JpGLEY/lkobh7cIiHbVgR1MIeuai72w5ecEfGopHzINfwVp26pFbQS18tWH/FDvT+wI2ww25IJo3kFjItsiSwBga5oEiZg6AEYQfgSUbilSkM4HetxikRcrdrpk3l3AIj0d/T+cDxT/o3XLoC1HheVEjfkFP9sHX8WDydbrSQRunFoUcgz3peyvZ/SFp00kFffvawhqgBpwUTgtfdZLbhVgFYonmw9SZ5SZRykDC0jbImSLhXMxNIe4C3HxhvJSiC9UIU=
        - secure: IRl9vD1opEnKINdeaKW5lELsjdWT2oHcvVu9IUzUQmqkU5SD5m5HzsDKLLXr7zAyL5LUDlL79PkGS2sAvSIvTQcBHacLwdaXTVdBb3m/x6F6xrG4Vl5zWclw0p1VTkQu2VxZd7vP0HSiByEtF9+Rf7c+ZQvnKdvggKK9e0ZMZ5tHv1E2cxoS79/VCfRT3EVQEuc6wYS2mKZwltwd/odtfWr/0Ogh6ymE97AQtH0TlUKpWpEVj4jNfxcJJm4LruYzQ8jsPV5oU7eYg3/CWMDE/FEmHMQ+o8ocUsYbYFtKi3gCyprM+NoqDYJD8vYQh4mm73/5WpX1EEW7Rc2ced+VZUrBgIVX2bb+S3LMNBdoIPD7PgZhfUCYtqUF0cxnrI53RZwlAXzIb/PWG0vsKDT+u9J3VQlCG85IzFtx9yXBRubERmQV3biUVjTTRfdlY2+cKQjGdBjz28D7hhSsA2ENv6PikQnko73uW9n3eI5cz9d/Kl2mwH8zhFman/4TjwTqKKbxkX1FowJIv0NV9Cz+/FY9S6i1VTGQNJ4EECNd1nI926dpoNhso5MQ+Bw2jOScJpL19PyjSVIDl/hdIQqffzkpZ+Zk+2+Y0Yp/vyflwcB5e/yJLZvclVEqZEoXbqrHRrZC4DbG2TfvmNiXjDW/CDOqgnFU2I3tR39outux39g=
        - secure: qGrLkWUmvIXGlKLBjiOZomBnrfajMpJvD9fpDimT2Dd4ClIUfDTudeH25YBhkrKv7ybrj50jUaYPkK4gxVLKcROY3hIGkXTJiTzkUv8pb6sQDZPpIcEBv8YM7CitSBpsuxjblAl/UPk+dBoikBERWESXS8103pZYN3GChtjOdtD7EJvXuz8r/EyrgSX3FmfDMJErHS7Lln5HQSNkAEkbHr/hoj+8nrdT0BJ5e67OSQydvznfMlff6qX1v7cH0FbipU7anRHhTcbkasLqF8NELjHQgdOF3Y5XI/cCjjCiDwW3+FRarYpz2HNayotu3r16VpJH6vWQtU8yKAi8jIU9o3OUVDQncYlYa8/UBuX2O6neEo7DPCD1YbgFdF7eCszK3I/hNMhyZGqrIcdN/F0Omf2KB24/OPA8xjsf7IZnhAVjjlYN5nxoM2gd3gV0tEF9hW8HJ+C78d/v9rcqdhs3WDMAjDWgdCZutqd/Rs9fm0wNEiSZE2TLLz1CYGMEbJsUQ1K4IIIfSinjh1wQS3LeBBeERDHghBL3geaMZscuv4x7wUxan1SBzjdNPeT3US80cZ05GNH1moX2f2ITFqNWm4Qb2QcykfYw6OlK2DHtIQszKdDmArZDzq4j8AXZf4bYrqKMDufgd5v93pVq7E6vS8FZKxR07Pd2n5ej2ATNhZ0=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: GoySwr8NA2ee00TT7ARUTVmLUgFkLzlWRFWVOGqCMCcPGv892bJdQueipYZQ1PfKB2ByFxXWkWqRRekASoBcuH2zVFBBgqXU7+2BzCMcpoiW1+M2N9iL69hMsR1BDPnOiJ9+pepYb2Dv3BLHRkFmfMRod4yXpQbYIaQLVx1EXbSYBUNvC2LdO9GaKhbp4ZCFHEBks2Gb12sBzklnYU2xcIQs5DZeFBo3ic7LQi2dDFuXPY9wEP2q5PF/SP0R0NQ7DFe9RzQKcBg2BYRsr/aBN9CG2boCyTDUuLSMs4Ei8vXA6iWecfYIVj6BHF3XMkdfc6vofILwb5PYbZVpKYzbkCUWPSFrzzvDagcOF9uBhVX+/9/ouBpXYySk0YCkyjNpmrzbhyqGAhX99vDUgVXTBZ5LOgqybFHUXmiXM7JpGLEY/lkobh7cIiHbVgR1MIeuai72w5ecEfGopHzINfwVp26pFbQS18tWH/FDvT+wI2ww25IJo3kFjItsiSwBga5oEiZg6AEYQfgSUbilSkM4HetxikRcrdrpk3l3AIj0d/T+cDxT/o3XLoC1HheVEjfkFP9sHX8WDydbrSQRunFoUcgz3peyvZ/SFp00kFffvawhqgBpwUTgtfdZLbhVgFYonmw9SZ5SZRykDC0jbImSLhXMxNIe4C3HxhvJSiC9UIU=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
