jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: GsPd3Rqn9up/yp1py1tlDgl0PKKAlxxZfcsrlWS2ob8vUAO596YC7fhFUDGYHOiT6WG/2mu0iQe1RrPoDxYkGOvWu0qgeSrpeHOXdLS6Ut80qD5Apa+EzF+/6XP4Es0JVjzYh9xf9u3wFc5oSmTS/WF8snCdZBJkVdttRFpv9583OnHkSV9iRSgNBPQF2K7kXEGDsOk7CqNspCtZl/9bqOPOnOyp5o233pC+47NfOImfzk9YlqifNpotkC7PSWg5GJftC+nq+aNsAbXjkcONVjRt3iBS7sy7kiIdSxmGo02ZEvKe1dK9hDXH9fxKbjYHLIeU8bLfICArDn+dxAowgAVrNZc3cjuDEoPcvW3GPVDC0bFjWqw80Q5N2pSUrgNF45NjAEwNs3HH7nLJZonlN9oYltzTanQWxxyJs1Kf+9J8vn73vjk6ftsYBlzjy6USyJX/UDf/1kiE5DCCCIsi/ObEbrzOH34/ThcTVZgJDw0esCXiuh+ZqYvqkJIhEe141rF4yfqOqqsVuZs8+Bn9Jc/Q4KutpoGP5DnUjdNLeQpfkDioH+y0akTt3rgb5ilsLBZqUVGjPSsg0STLrcPgdV7LFjKSF9HXKl62bAdbC8iAGaUc7g27sLl9W+ShzAs2ESn9O07AkutWuwSxu+tYAJHYQZVuXijUgbsMDjSo/Bg=
    - stage: "Deploy"
      if: tag IS present
      script: python scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: nu3AWAydncvvRxfhH9VJENqvMqNoEoaJcdXaancFynLxv+v9aFVhAi91iWegjLB2m8Yki3JK6LnY4nvQAASGc9HTRq5A8JYp/kWZXcNI+LbLpConXooU97w5Y71chTi0QCw4CbIOzLsOvbKXaS0ma000uSIPfoG0P7RYHYQ6y1RnatJvCxkOgFx5vd7T9+dekKebvWxPb73eoW2qZAMrsTYWegQeYQObrIhUnP6KJObA0kMSFL1d0lMJecn5ggDqOhO7/y9X7mQl0i74ATXwQRP/XCcm6k74T9JXLF+N1SsOQ39gGOI4n+sxbOccUcQ3Zhxi4g5zfwmEF3/vMgodc+nGTLjNyCtd+TDJS2CjnhJQmUEBVY5AlLHUeWAtyQmj8m/ONU5Jx98IaxCoczpYOsqNuxx3B70SAGQ28GfD4wEcjke6ySXbbWRzqE/PwO0HNQaD8VgDnFugJiAP8yYnfGmC0gSjjAG9GU/UqAAs6L9Zhstxj6fI0x5gNugIRKfHXeW/V2oJmInzvpiLRTuAFeQENZYb0H8q/Q1shNBWe4xt5SeRVFUJrlxbErqA1ao/9T2wZj5QeBDbBlba+vk9m/oSP/JjXFqvK8iucQ6qeJX0ub07TowPvvq0Dz8wSPRcOi+ZI7/mZdF08ZkFrN+a/v7i+8IdWdyxpePCxweXpAI=
        - secure: ec7/URUc4jC9MxLUSuh0HUDhWOgOMq1f2Kt0MqEbQmIDSnyd7c9zO4lP58be52Ge/QXPX2Zu5MA3KZ9uyihTmCsKpMvpteIoT7x+6K6KAZKpLee+zdi/lRAq1Po9stFSaRCNx82e5Qn4lctbB3sEmnyIEHyRhn+rvnPxY+FchU0bmlpawbjpIW4uSBBojG6D1UI9FEB2XG0TiYKRu5PumLQoS5lHBSIFNq4qa8ZyeGClDTwSB/U1Uj6W2YaNkaEWetWYk8OLFDWVD72P6Kt4F0TF2qV/ZoHa86GZgXm3hP1xrCSsehyQHAv0aQjQwduXgX7O8l3dOnqPCo+YkGP3XuMa+8qPlS2Byb4yM2mocBgbVbTYK7mk9ZcBBdEQfvUqZ17B5QoSIU0scFFf4Jb2wFSEoQA7MbFaVpXS9ZGYrt06S85Vi3UqTmi/WT0kjhAlz98f/dsjHn4EQwBXflofpVpfvXOtg6po56k4cVh60IJ12FP9pdkHVixYjjtKcQxjcSnTYuy/yNXI59hltKHDgrzNAJN5gauBXUe+FbVSpZXHlBwY5CMsFYMqq7KF9p7Ck0JHLWgOEJFrFhLpURRabpRHy/FpEvxH0Out7kWmvq8rNyJhlo2HeJMzUI8DLtC6Xkv51m0qlcaow627ijKx8s3f+5ZTaTZyGBZAoCRsYOU=
        - secure: MIpzF3pUVHIBQwcWOLGpfISHDmD1VNJMt8fXVsqRGyDVzpC6fBnXsGzLJrkpu73kbAXQ2lcyMjRphPz69IMConQ//ynqy8+Q5tjJFroPwdz/fJZM67R3Hd5wawHnEu73+A0rrPJg4SKTB8b8TS+uz/rqoBQCN61W+JUBReG5B5B9MxsENH/LJAYGA09LMeVXn5dxdPSsnUY/2kgUdh9KWgH7Er54VWBs7FkOhXFoBuIdiAyHeyFt3e1e7EJSXEmL4+ugfozM5CTzWVTVDBlD7nVSoMy7N9miEx1SmWqA+/SEjC1AwIk0y0UhaxC44JrPRHHGajq9dTIb41DNzbUKRfY3oq4OWe9bpBFpzL04AsGsHRIaVjqPVCi27WJ+DzyqC38iAWiKyJRaXr6RgH6ouOZjzSeGiNMP0Tk2gM0Fpomu0KLHq5sDHUSUSKf0asSRtmraixfQpt8W8nPAbACuwOIpBe3L3Mla/4oqJ8ir/wPOZVAqCps9/U5W4rlDLhhnSqdW1msANgwGd9jVAO07qD3PK6cLJLKZBniaeI0R+NVzEjQOwZ+nyPr7M1Y42gCXUOzXNKoleWS7YqloLWAWWzXLav0q/iYrQX/s3Eo55IhWoIt1jQ3uvsvpk9jQDorxOb9RqHDbpQ0IA8RU7UerIdlXM22MatbcJWrnbmAnVsI=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: Gkt2/kzsgT6aobEO2YI5suo4FUQ2HBoahouVEDAcmqZtDiD9QwrLG7xHas8ieZZgxARqrMPDNbtK9hzMRGPnrzBw9s4nRzqfoCyEzvZlPHGKBpnmb5SmtOsZ4XAZBXVmgia3Rg+8zZLUVYxWuTRj0BFQnS4omX0KDWwFELeIT/qWzBq+yzZbDIT2mmUpbQml+2xzHbkLI0Y4RGNy1YdNxLFL0WDDrbj7KaTO6+skDJ0Nk5Uz2Le3+S+7vtJV9Zv4QRxcRSqfh8nmQ+zzfGp4aKcyNAhvWWUxrVzFGApliGV3/nYveBlbW7zvUX+hyFamhNQqE04BTnoe6ReWOIQtr3SH0jzE94zfiJYUepju8yPHXDywk4eFop3W5qnw6bXLA8agPtWA7zaOwNmO3GBgom/D7+ovPWxGNL67ihT6wqqC5zq7rYEK97UcnFAkyvLWh045qfprzE8Hk+TUmbiSFPN8bs6SL0uMMR8BvwctrG+gqD+EzfvOi5C68VJKI8dGjBdr1sTC8yxkLaBTgvkOTaV/MPiuWeGRCfNpIhRNjwZcPeHaY6hVgNn1RWkCMEcV8H2CDmKrTE5n7oOnjo1vscCZJPA5OvyaqEQR5njs+6S3IHhD3tSXf8DGUUCcu947PEA3SVc5jyaL7XZkGiMBdkRMELraHQavIkFdVoWXW4A=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
