jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: aDSotdtlzUtHLWgbqdPlZzVJ0thY1X7ysaNQiMIBLcYM4qANMEvVYUEX2mgbLwy1zA0+CBouM98YQXRC5NQpUMkVMFkLsgcVpflwI6sNiv2Xj6F6wazfx/xNSaTFBBlkjuZSVPs+MDbd8tFXjdX6NdPzDzAU2oLa+EyDGM+Q5yIb+j9y086EpWOte7VoXNYnfCz+/DC3htGRmjYKVkI0jwKqArYElrgpztJqEEGNDAo8dI2XQoYFRuFWuNLrVSvSNhQD9wpSuFtuedEcE7RFNNIydP0hAhFIqRikOITBcxjGhNzF0wEKu/dcwsUtHfvyVM9bnQ/jz/zPlHFSgqpNsye3IRwz5oQEWbhHuQCEIrYUdWpxF3q4DHQHCiq0fy8FCP8/RZd0XS+HXb4WMj9/9TSKwTr7OrrREU+xm5Rv5uF3yXNY25aijQ1ui9Aks5DRbz/p5YazjJdwS+tUBQPLVPNlJ5uyHSGm47GS9fH6aRaN83YQEbpTlna5uv8PArq6EX7eMQuyEDEWLgGbATFfrTJdX5UEVAHACF5T3cajBJsmVo2fjZ2fkQPV84LJxFLPRuPohTumBVc+00vj9eFhvqgzSvxPqMdfrY8XfVX/jfQP4Wpbc9rnmxvkJARYnMILRhkJYzQsArV5GOYsf6Shch0Ytdd+3QKReunV+jq1v5Y=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: VbdLoPRkRQMfO6BgEnerQbMC5QteRwTx/tNII3Ufp+1motZC9LeMhYNolTOKzQbAxqTpEvNJz1ykWyEFF+ZRNZ6VzYe+yHlk7EauuCQjyXNCU6qOU5oMyfUtlO0luhNh21E3DY/k3K9R+Mj3CfftP+BQO0QNQWJFK0OLkje+B9GRE1B/zW1a1fAdf9bhaNsVny9Jh/KRAnMqGjxrvujAXWuZZqX8veBpc4hqrOuBzZajv3rWRrTQCzhzGt6eMm8qFYQCEJKLlY2kFu6qpE4w72AaQU3eYeqDtLce76pC3icsCsfuwh+ZUqUVk3rJ09Rqv/kGEWB/KxWol64cXHckqkVmfw9Cs1KHbBBKHuri/f+TdGXc4Ob7XLmyciENXl3Gca+n44uUHDVEg2YntlVRGKTyrn5AOr9lElyTb7A52blHEJYejxMVXhARvosqQpj+/+L5vLd3CJmLSG8Y6F7CLI9tqrFutmuezY2SKBM4/Ceq1yFoHw1V0tdHuYHRZzVdkD6XNgMU0Zg5f6vplje/pKg5TGGhI6/JpmcrMrYdz54cvhHurZ8EHL72dFluSvR4IuX49Jp3LbSISWRh5l+DeY0GLxHaJzE8aFVck7GUfD/PFjJeE7kl7Au6eYKe1p7gDdessvfNUJ6YR6wcEhrxfSaz/Q83OMhlzBm+LnCOnCY=
        - secure: JeyuRMvWzr0DAnXkD6uCCWF54SpwISBRXHxekEk7gRAnlLk+wxeMC/dAUMZ52nrM+Fh5xTbxhI9LxRFj1H8nPrj2/USwHsqCffiqAnqDcttc4moOWg7OAsVMYKtmEYsRCAPle+/Zna+CfA/oc5YfbT+f34DCcN4/VnGhhrT5NWa120nGfBnWCKVMrbcaa8mMPO8eWL6EjP7k1XEk2YpSbEKgVZfbuTQvXnpfE2kum1B3MP99zmxTFQSm3FjJbM9csrj9NQYZDwxYZwoPtBfK083ZIXEv8aWqJ9esY/thMzXHyB4Pgrmno+mJaBX3DS00Dgsqn9ysubfa6wecE4TyK1GN5j3wQ4EoouDanZA3oazAsUNnW5LAjXIFF27vi2BSgqbwmHW4Usx+nvV8aGcEqWUV+Xk4W3XVKrnDLRcjD0TaMirLdAzxstNMEOQwCHXjSSdB5vijGowXVShUS8XkXjduUX4DDP7EVnJjnEDyWlEWfYwyQg5OD7ummV2VrEo9aCYhRnLbjPz35gTJdcWR5o1D/Ez0WJSGu2lYBRqH0hBmOucEJiu3+L/BXxgy7tqz3vqNcqJVuU49UyauRIwy5W9k36OcVVOxJOZksAdH09jn0FdaV8ta++djPUFd+B2+h8wiDtv8NtFgjyWHRVikXZ6Z5+p1iYoGZqdQiDfeRuE=
        - secure: VtxzvM+jqIg86frI9IKrk55P4R7Ku1cyDlAbfdFUXodGPilnMLizVjKvLSuvfpKBsTJykXeIElxIOJt5QdHuLka8ej0+Df+EaTLGHy8PLxjrbXOIUjH+5rCmvolKUX5FIAQKwsmO6mxSU+xCOK18M/4TyO6ehCGqBPHmdm3IEoZWdW6p7Z6CbYRXtpmnyn2ZPP/8Q7RAfWVS7omzL5t95/5gl9puBuPIs72W9vIn/1kQp5qAPIDv0TCus0AhZasxTO0PjO9qz6QC6WcUY1nHh3aN8DCstmH7t2gdPBqFInG+3ChgfNdxpa7+1Ij1R9Sq4/5Lf2S8yKRGytlyHgzkgTpi5iNk99GbAjeoog8KYc60IwjQiaSA2htZh3zyOVU38HQA3GUH/9+1q8m4jGzIQ3yRg+C6qTS1fE9xiJoIYbeIucmc6eL0OwLmMgdT2zrCb+30lHsPLm6uYG4pPAsifhm5lLuU2PIQf6iKZOCa3kFl46+4nhLGvyzwsmelpV9lVHTH8K6ADVwzMoXoLbAKuuEBBzqr/L/SZ3mk/YV4D0qgS7v9rng31QH0Ul6JiUAebaPAnJzLypkkSb0z4Cka1J0TR0usTCigxMVU0M79U3e+SPIjsHT4lMIRETQPyZXG398XDgGqLnPJJYc40e71nP6Qlg/RXfz0ubqRXrFKXGs=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: vhPbux9z9TK7sbKO1XZygRP+aHfb0JW5rCWCoEoBUlt4jnjWyd16mPPjCPSZv+ozubYo1koiEAbXNvoG11Rcd/kYtJ+MdpOwC8XgjfKDl5wqjR+zMxi86UDOQ9ArvL+meK+gknYfOzSA7DjxPanXEaPxZKDwMho+37MDnZTX376JVJmkAcd6fWdvMwtYJnUnn2d1gxb1WChqLIEGWA+IscCljj2QZ+6uirlbzHwUBwg702M0P7IGaHt2hvmVNDGExiw01Oi3u4Yuz3JUhVP6XE/Fn+lnwgs3yAiQS8oDC+pcGutO9iNyEt9nFwcZe0Gf4i20R/KrIY9EEnCoqVT2zP7LhNpgzp5Z54PDlFRHkIl4J+S5YESW6TdVdgPqOJ9jv1RksPGyFKhrODbFzvraQ6dspJH2YFUOiKMHYBojR2OdYxYJWweoNtdYy5WLLOjjOhRsfFyRqNYUC7Sj1ituCSDbiK3ad8Ax5+ZJMUImSCdp86vvz4N0f5uBdUjck7AYrqXHBk6KdhttKwVq/8SRIB6HPTyMZ+kA4vIEjdF49mgCHit8SIb40L5N041OanZd+46R0GPAlwJGOFMRI65a9jEvnJ1lLJYUF6GSKP8FeXBvvdm+h3fCHp9XkjIZju9mRDFgRgE+9QUiZsMc/Q+/Ns0bZYH5wlEpvH3BAQdxvSk=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
