jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: V9BWDE0PCySOVJ2L0Ii/Ln5Mkwu6ySM+lx6yeYL13QfRL5afWgCbhgpL4SuycdLCHDN5T/TAWCXl5zKIK0+Gll5Mfur8cl0WWI3uwh9gfwbHDQ3HcjlpcssRotacm7zJukl8ll5KA93/t83Z0TnmuR1nP+FhNGqEMh1g1EYCE91lW6fB4J2wpIDWSmXcYBDGgZNGvaE2MlyTFn8lB7+lfuQSsHqRp+jhasdVhT7+1AjS+FG2r/5Umj5UDo1cBTNw6v3/TotCn5oacLaS/SWrGa0I5deJQc0FRoGSnfDzWkFH9vBA9BqavVMhSlTpdgn8+GNXHO9VqfSBlcOW+N0zNEnAaPMb79cjwacFmBtSYBw8tUwNCGkRHa1rkdL9xyehM+oXDK2QYpZHEBux0vKdgvIcFk781nda8mmZxA1nH/VES/mZQb5b1Gr51CaJHPljymc0y2W92i4ysirhIwGB3O5iZXqZM7ynf5QiXVjA3sou1v6nPx02gr1m1jNqPnFfadI2H152HDN3GyP4OnHIIXMyk2MTSsKCCCbyrKjBrh7STTYAg+rodwHoXgA3IZJrV8oInsE5jpdPWz20a2YdK35XHM8A1fMmo7JO+TbBrGSv2lHift51sr0QRegBoWuXTJmQpaZHvKzcw4Rh+oASgHx3krQldXMYj5URhEWyBQs=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  email: false
  slack:
    secure: u+RsMHAk7STThzwtCSFRSguE9+T+pi0zfE96CvfMvddBPYruUqkOfCM7kB5YrzHHV5G07Py4xB8DWYJ2ZvS0dBZldHWgybFzZ20YGY8ox5WOTqBWj+vrbpIO3lTG9bNE1ymUAMpLcJNvOilsCDriLmt0UBVYSPGvkYHLk9B0LH9SN8/aah2teUGU9ZaEizIPJ8UH6c86dP1ujbpgJ1B+rRiiO6saU5KfVchqHW0cwX6OPicnjg2S1ufKz2OAQWTh3MoRJ1KHGkwZq70BhLphpraTtbjA8HDJgnk3MtOXIumOkmtjYbJf40ULgru2H8ENGlC5Tvncjcb/0WVPzfS0o6ngqZXO3kTaTlKAtTJK5Z/n7XpI++9JSz6DQhHBWnC9FQnMMHaZ8lPzdRRK5yqMYm0L3qvFFdBHhP7rkxSHG2C/tyo9UksA3T4XkAIwYtshUXymQmtyV/5XqgoWaH3tQ0Z72v5WH42Xc21iZB7IF6palfjeKA+gsX7HT8vpgQ77OE1cLx/1uR80xCtJI+zE26JK1Tr/iVEk82gmNUQdCqQ5Gdx6MQrAqWiDU+FA2lJOF6yqtohc3FdfeTuzukH69X6iJXWhAySUT0qFJywjWTl+1YflrFdyR76c1hVOmvpk/9Y8fRWg3NlZftOjGmYpMCqQIDs3qYHpXo+NXZUerO8=
    on_success: always
    on_failure: always