jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: FXT/D80G9AU8g6UAvz14uap4nKx81YCLFwUTmzT6bSFbhgUyp7ZM4UKLAFOe8ivXkxCo/0ij10TI6aN6c2svBcW3BqLlKhqTozVJacVRXP0QHi8OvVTcT1HuH7FsTEHlP/1VYtlZCROsuVBscYEGhPPvcdg73o9tbZwfLHs7hWRUXe8yT12MBm/e7mBjqfDyWU5KvUq/PYuU4GulJsB2RoC91iMKbtQ89XsrIdrpAwjXQ0cdB8Jw3PF0pb2YGFnOSQd+froRS38t4tDa49h5gX99aqZz7D3CxHRFhOGz4L2MZk9Ukuhct+7sS+hxODc26TI6LyKH6rqxzytT/lxcQBAroLIm3V0Wsf/XUMHDMGPT6IFOoiXk148iCwiko5uWtioaOjPqeoC3jmgLPB7ZTv7ERh2FOT+TKStRsQF2pfYbTG0J+A+SmWoE4h+H0k2bE0s59XD29/ihtjFkZS7EhW/RdUIHoB7EIFG7dCgG7qbkuenwp/k/yuG1XgdFAsYWpSf6CRc8SXF3oz8JYZDk2z1ElOm9fltsFyNsqdfeMuPvW7Zb2q3QCEexf3Yiw7b3Zm/JT25UgkUJmy/4u8LKECoJcr4Fh7HJJszK/XNOETH86RNNFsJgaRosor4jsFcWur8LdRwdXdx5jLtAM5ooDaukmZeqfYI0h+faQz27bGs=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: sm1Y5Z3z40Q800o/M1NwWD1sYtUJUFGZvVMfAt2/bhvfZX0LP8fIpBK2/b3Z1kc+91O1MjLzXFRgw0mT4l4VUtJ8O06cWNlmJrSUKUDOzTM/Tl8qfw4OtMaYdqUKmZfOycFfRneD3+zyOzT6mrxTApA1MkcSs1BCEE3NAA0KhQgud77GGby+vqrwUxnMgTNcALsZKAgwXkZzdkLSYSj2p5Niqe6ck21lTs6tNiH9VVtr1aL7FKUgFxe0Ro1ARM/1bQ41eaONHLYPt5q7ZeJanGhLtLCRtCCbpaPc/5TLJbtbhSI5Vuk0bYipUJbO4qiVB5F7gUMRYCXXAmCFhKj8BUKMwfFGoFx0k0lXd4iPXgZ6KYuVcyo6IQLfhPpQoEUaBPDS5U7zMMBGOeAVSMTfm3jV+7nDzn78vfNdl8e6c/MZ/2/EG+9Cd175tn614BU4YWSmN1h3jv/3YHjWq+vkSbmMl/58je6urX9XwWD7SYoXwmKQyGNrsdCQD1EQEkvkK6LfvGpeW8KO6QtAVWKRdfJn/+Cc6XzMVa0H4glycnmHccRNcyFv46gwH5Ltxd2nD6sFq+Z5fugo71zZLSGbJiA7oz9H6rMwjR6PZDpjQ51L5/kbsifYfwzlsIzDusQcVn/d1Iq2NDbSQ9Yhv/I6b4YOVQBES8EwNGPHjiSigvQ=
        - secure: t8aZWZE51m/vjaLRx9vV4NncBu3Wqfl0dlcvRXEaVWD0Jc5hVi9EISwCjNo6av3bNvuewNCx1SKD41VdaVnlFY2I8122zRqoyXsaWQYEUYExm20VtsUJ5QXXuEm9mkC4NxqMgoQeq3PwFnDtsyteaiKzkUK5Baar8rfU8TZJpaKzLL+oEn+awRIx1q41ZnKS4TosXfl7vKQWY9wVEyTfR+Rvf77FKHGbcaS0M1N1DlHoZEa15oqakDkVXWOO6fhMH1O/BhOHd/MRnp9FuO4Xl+7nCNusCV+RfplQHAH2PhV+C1DUlw3IwFHnHfDslnNtz26hY+q38RtqTKXOc2se6hUzz4eONMRa/BNqmjGmO1XUwGvqUrnaHcBX5uRw1aXdOtI1+9eFmWRLfW1lUtZHazaJeY1wK52rHiL6nEOUc1SuXS/kEwhixMpWdjI+pDgEYB+U0L1YN8oowgJU920anJydIY+IaLWtgl8Z9iPGrjCzmoFnvICx0k/AHDx7aR9FRBPJ/0z8sx4KqJg/3awLIXF3ZSglkVSgjuxFE7iHPbSasg69AKUd4QiOZbjs4YPeYvg6MmLJj6k6gOS05NUiE5mYm11rOPj3MB4RWrfqHQx+akibKPxXQDZG/xCjMXlhvaMfdphS2etza1vOkaVLId/aNpQJnmhWyRu0yXh1nE4=
        - secure: uJJ29zdOuSxyF7nduj49Csz9wUs2Tq4unu+Qgz50ytEk+MC/wvUMfTClgNNTvIG2S5nQ+TiudOrxHFbIbC6Pc0MuVTJIfuJuZt5N0Xnu8X9MYjN1kNWMA2tEIfShKf1dy/F5+KFEF2Z8GVjZn6ofTZ38xjKh9N/33LvQN60BS717u5RcvXLLMQEgx7rWXAY285L9NA3o7vhvCYtHuJj6L0lkd0IRLpXAfvE5lNfYNJE6XjUsgGSEpvywBPsUzQc0xHYVkb4MPYVEkngr79IMfT000XX6s7BX5kKG2UuNycdu2mSiDyZFu3yaBCyUbHWrMBqJUc6Yn6WzUrsbB+TPhcGzrWtsSLNTeI+WIY5Dj6Yjp0iC3n/uo11WTabutQzaFDkYkPpmuqOdWJXD08JhKvTLjqDJol19NFQnYHc2TcJxlNSYMgDgrvV+BCF0Z14HfYAyu55nkS1exG/56ernyb692rOtZsFcpP07BMf1q6yNNdqs41YgmNs3/ebDyrsWYt0ZRhnCxIIyGt4jnO70Y4iW5vphPkHeT4Ke76yQuJIBMDqMpoNTNX2j63YsQE+XGhewlTiG8Cmx/6mjXHyEqIR46HwQIJQv8ZS7w4RgX7SfKKymai/40K80AlSrKankz19BFi2RQX/3yYi3qjHhbRnhSwn7OC31wVqf+xyvxxI=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: c6PTO+HuWf8q8kiqAL5VmASXtyES/kA+M7ZpN9PtLFBPBvEijAC5Kd2erl3l3nTNotRODnp61YRPSsG5jFpMndNIOvZWKawA7TWCDNgsr6mUi004INENrjp9BZ2KQu3bkMw7ZaCjx998K5f1TJzZdLmN8ZCsSKlHXbjK1ReDQdjyq7KCci23y1G90nIalTvOsTv4c5o+0bLRPEOm6XwA1EL44tI0CSIeXcJSn0eO9XrBC7+S794xaqUQtAhsDYh/hRrRmLMQ+QnwkgjX5sS3hbGD9/PhycwuoU1fskjkSlIGKeHC860vK3RQ2HHkITai/tLwsMZ2TmdvcXP2TO7A0d9SHxvYLHSHVuVcWfDbZpQnH6faS+CqfBJS9bNd3hT4Z+uIyyjwFVGdt6HKGC/PNjpdy70twYS3hfoxyaCcDyGpptzBKrPGGrLirXH9GDUL3YKF27JGT8mfev5Zq3ElMWRwngLMk0qMm07W3aU7cJPAP2NMyf8XwTSkACYlIwqQpJWpTdCYadZiz7DMNxw5bqoPsfRIk0O2aUj0YgOlmwhesyGQN7z7Q0xVMR/YztXhop1LapjgqVIjHuzbP1PD24Z1aVEJybeVc04yrVO1Uq8D1GjquOcEM/5l1NUuer4H02+kNDitUZAByn0w2FYXaHnLhBL0Blsn2sHcT0FqMKQ=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
