jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      sudo: false
      python: "3.6"
      language: python
    - os: linux
      dist: xenial
      sudo: false
      python: "2.7"
      language: python
    - os: linux
      dist: xenial
      sudo: false
      python: "3.6"
      language: python
      name: "Test Documentation Build"
      install:
        - pip install -r requirements_build.txt -r requirements_doc.txt
        - pip install .
      script:
        - mkdir .tmp_doc
        - mkdir .tmp_html
        - scripts/generate_api.sh
        - python scripts/copy_docs.py doc .tmp_doc
        - sphinx-build -W -E -b html .tmp_doc .tmp_html
        - python scripts/copy_docs.py .tmp_html built_docs
        - touch built_docs/.nojekyll

install:
- pip install -r requirements_build.txt
- pip install ./

script:
- cd ./ && cwd && pytest test

deploy:
  skip_cleanup: true
  provider: script
  script: python scripts/release.py $TRAVIS_TAG
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: fTxYi+g7KKlH8Hhs+r+A7FVoj00J1N2IawIZZNB2L6MSB2/puTL3QKOVF5IprvwKcc2lhAe3dPMinhDYgoBY0AeibaEb4GFf7pGJhnN03sdxTBWMBswePf5eU4dexdpdAMldsqffMDbd7Uo22+j0/k0RhJhX7nTvu4GbUFtv4Gh0yh2nw5dDcD3y4ZLRk1SOAK8xErBZO8x30PNPZze+pjIyVcxfkOE1x2P/TfkY1bkWLDbts5bV4txb0Ycu14uS7lWE7OJvxOltl7fBVLnoCrD36fEtdlQes/ZtRqBQJAbDEXtjCHiJDIm83DY2Oh+hrYKrtIFllfYUlNn+gZM9Z3AWtv6zKYKR18XtK+TqI+NUJrAjsgECgy+RmrP2n2DDnYEFePI3YAAet5ssFv0RkE/+7eJpHZFr8mAopyWFhuxUPnnYHVwwTDMk7XFIGx6DCvjH/NDBgFpEXTfZlJ8E0xscPcUIsHr5B6k6FEZa4Dcyoae6OJ2lYVpHu+MPwA2ohGyaxF02HwLRD2ZGfczWEUTYsbexcV91+GyW/SuJHSAUE78fNu8P/WzX5LwBlmcvczTKwpYj52co5K2r6embQ2WcH0qt2GqBfkQFOl2eP00AgIjyJ9MXJD9Ai9YBbU1585jI6MZ0RYt4HZQsujQhHVSgTf1sy5wEDbhPUgiZ12o=