jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        secure: XKjQnd6/3/HRzL4FsYFgohOM2xTPoisncoQqGxB2fEcKoy3Y92vTOW24M/N24k7Jyp1JLHC3iZER++PVNIwZflL04uijyu9fRXmLT0Jdmv/IKrSZJTPgRxKoRKfUkeAR85oDHGCLA9ZbP5BdupInwS+R2eXX7IofXrcZKFEdUZTszZ5i3M3lA+WMFm0x/CZSxuJoeWKj2qoqCkOttrbOWsXmIBNpeZ3jePEt3UwfTr577E3mDRRWJXYX8ZQcaDtDxKo40A5WdVZDsm61G3scTDX6WwCo0P8JiG+ZSlaZkm4Qe4COUeNM6FY+o53wDPCv2R3dNAQq3DDZoeH7mC219OTeGgnb4lN+liZyMAl9vHq5VgYYDPfqTqfmEabAVCba+ehbGvreJm8ra9SBZwujySZEqgsVIr6Ty6it1Tr6IROCn8LfwEsGGnYjX+CSVeefElnm9i6yZpqzDGBiJQ1DQAALqVA3+1wiqkfKjmbXuYMnYU0Pcv7FkA8fhuLHNUJxe4feDNYYOVqNr08zCDq2G+nTFhnTwHCKJ+3ulzK2QxudHNJe6ZjjoTC57QQxlna4GNbcpdXzK+UQxsm4Ni6CR+LRz3ymvFxWffHYS8+WusM/XQt2smowixbvRPZbp8+b0y8vPafSjyeHUd5L4E7u7/3kRY5YjL3O43cN9rb7F3o=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: fTxYi+g7KKlH8Hhs+r+A7FVoj00J1N2IawIZZNB2L6MSB2/puTL3QKOVF5IprvwKcc2lhAe3dPMinhDYgoBY0AeibaEb4GFf7pGJhnN03sdxTBWMBswePf5eU4dexdpdAMldsqffMDbd7Uo22+j0/k0RhJhX7nTvu4GbUFtv4Gh0yh2nw5dDcD3y4ZLRk1SOAK8xErBZO8x30PNPZze+pjIyVcxfkOE1x2P/TfkY1bkWLDbts5bV4txb0Ycu14uS7lWE7OJvxOltl7fBVLnoCrD36fEtdlQes/ZtRqBQJAbDEXtjCHiJDIm83DY2Oh+hrYKrtIFllfYUlNn+gZM9Z3AWtv6zKYKR18XtK+TqI+NUJrAjsgECgy+RmrP2n2DDnYEFePI3YAAet5ssFv0RkE/+7eJpHZFr8mAopyWFhuxUPnnYHVwwTDMk7XFIGx6DCvjH/NDBgFpEXTfZlJ8E0xscPcUIsHr5B6k6FEZa4Dcyoae6OJ2lYVpHu+MPwA2ohGyaxF02HwLRD2ZGfczWEUTYsbexcV91+GyW/SuJHSAUE78fNu8P/WzX5LwBlmcvczTKwpYj52co5K2r6embQ2WcH0qt2GqBfkQFOl2eP00AgIjyJ9MXJD9Ai9YBbU1585jI6MZ0RYt4HZQsujQhHVSgTf1sy5wEDbhPUgiZ12o=