jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: N84FUvqt1YwZHUyob2zBLtF+K3NCZPOnO52G5AF3R2ZbcM76Pq67qCU3ibmyd/giETkCO1zHxbuJ3NlhyZukZFJ5aa9cb6AV/ISzys3W5ypzwZivphkf5TcV8eQIPIb2apQMDlWYZSR1WcSjeGnX6bLzP6Lmkn+4feCIk8672Rjy4gDjMWfYl6RzVkOtTzf+U9jT4YpTj3IsLlg6Iv45ak1fnh/u+OI43ZCmKiNJLJ5K4UUcX8HqEwPhGwqUR/NirIbWcUKcxASUMifstZ1SvzR1MG0JTC3WdrA5wKO0rwn9rvYu4VQxKAOzGGS/Jcd8j90kuCQURto95LdKh6H3NjAFcXlejpnTJOUg89lPtlgn+WXUAU2WCcYG6BX8RB7p3cSJn1u46nyCqYYfimUiO5Wrj85j7uXGLcp5NpBC5sTW22bnuRM4unWWoPdCwbmUl07kGHvM7VUar3Tyh9czmTJMFU9673BlgA5lHiXRPOEyjw0GHBAd2116IC3CqRrb2NiuHRy7qRMuzZ5sfozxXTqGvp/qaRs8asqIj5cqg5XPTI9WW+UJZm77vUyt98AwMlDp9cyVWTCIfM34AA4SggjTfmeXTAGyy25yP7+hxqdN4C5/MzPeS3HQ5PE8FKWGGNM6QqqbfT82LSVfSkgn/vkz5gnHC6lUHvKeUUCf6zo=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: DO8iWtiiv5lG2AEJafDoW5yVFiwk4G2eoS8v2pvJ9SK9gR55GJuu4qDBd5dhTHuqRpQ/MkTobllJ1qLA+ZLPPuaIK1J0GjCceM7LdCx/RlXhdIJajXAgaEY3KVgVNjl0psQ/MpbGyUksxlFGU9fwXM5h+r4zLDyW7E+MyT23xKbq33zW4qJ+ETRj3jFroMLMG7D0MJIx84aOsDBODnQwe5HN1xAnwRyozqI5sKvoiZo02aQLZZF8CJIV7u5JAeEQpa/odGS7sXu81ptK8RAe+8DRbs0gVzPRN80cCr3e30FXNjFUc37V5NPWH+JFg0ocZe9XUHFJCnl/0NiNCQOLSaUZ0fJBJuK1AYzPam3ebFPgb6VwwrRYl4wCm7YOO031xB5zeh0HZfTnMl+V4b/S6uWGiQT7yM1WvXZymm/0GkJmSmS6HNkTtOPUex1O9npaL9IYkTBRmc+qjfxP+JpNvtdDN0OAtFZMgrgFXwn+NqCM6Hn0W2MC2RSNF/9PwRKXJw0LZoFDA9NiOlcpRw1jWU+SoFU36vk3a0mW3JIlmHVoMjo6jclV1dyLJa01JVext6zCe2M+Zwj0XTdyuIz0YvRzzM44/QSfPDiLheHr58I5Mi9VHJwJF110AyFGCKDHsGrh7afyvaM+u1XgUz6zRSg2WA1h4ceosUfE0eCsZb0=