jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: vEb8hc2zn1RhqvQ9lrl7fhZwtfAd6ZJHLBhkNGXExvS+zcK2V+iDIYLO/9A92wBxWJGiZKGM+f4MRPUORXwBpyHDYW0eQ3ceI4mD29+OWLx61rDFqbleGzW3FPM+oVzIJTOou0HbrPzDDAd6HNOn3RTUwsecQB445tg3CVC21wt1UzQSG78m+OHYBtw4tMLW5mh7YFB9v0Y0dzJESkPQM8oVtBHpJLvyAqOZcEEnRjZmyF/05heQAzXccMx0iM5Qcq7psoV/Xuict6azQ3y6R81LsX+KFDSa8rYwg0uRBsxLGY3zbCABKhyp3HavmrHheaMBhR41oEMNfOsRtgmVnIy7QczQ1zQSlyU7Ej/cvk5wAPdV9KF/8qQDHrF35utBfLERkPHThnWZxaxNDqfy5mxh2rxqng5/kYjidZlHkQ1NIH7jOe2fFJLYE+A2gkdqTjgDQSpi05vVHqOIQtn9Oz6YBA6bQ4kdeLbE8lQdrE9U3XXMjTpJK4LvH6Ao/r6UNBs+oj7C4NfVDaYIRuaJYH4djBMiDyslKfaax2rTeU8ih7BHPe/okzklCrfzrWVOMB4zbSkUtkav9uInd84v0d+Nnen2IOqxPpDyNScA6CF9dmEcXeGHICI4l6w+KQhO6sFVihN7Ws86uU+xcC4+88/YZ3ISR9Bko/FTfrSiBYE=
    - stage: "Deploy"
      if: tag IS present
      script: python scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: HzZGXLEew8cds8iY9vFoSDIkKWaPYG0wjgBqw6gC5ZSW7bBihA9VRQQ4Mn0SWC0/eiG84oWyYW+UQy3Z36n3Hi4/kci9VhDKZm334XA3WZ5pWZ7yWFkOg1UjyORjuuBL94CqIo9DRD0UUbkTmoIAJjozxTDG3eUp/65HqMOu7j/BCSvMY0Kz1QcE7lf/Ck7cgTTpHIC4GScGgaloqcJNm2Mk026vxebvyqc+m2J7ldLxmnXD8CNmcaJEZnUreVA1T9uuPmYW7wyY+HO36+Nkru1yEJvNGoQ0b8tliz8d/IVr8rf8OaPHa8D4JVip+bWWM3z7ORX0rTeVfLhzXI6ND2UKISSLcxJo4wm1PuqA7uzlCALt2d+LLObTRuG4rl9zcwIuI79+Ak9EXS18UG0nJdeP2Xnl6UYIEiJyJStvWAMZpEkhy2RYJHAGnLZRuobK89P0OsDFH5rB8DRCjKLTR+MWumgGPTRAYGuXOC201XOOPoBEJlZw1ThvyqRrTWXE/Vz9DOYqjn8C8AMeQkpHRQr9NFxuvNbhf6jtZpAF1wPJoWYMgneWtz5vgdd3amjbJakVqzzNMSc6AB3YLH/N50c5o+rjoSR6uyMjxR2MBqL6zbyGNHnoQUhxZatSlJhzrvdwhxcHjdF1yUeZY5wdx0rLCL4G3pEFY2jTUxq4EnY=
        - secure: pEiW+kimX9IUoyOHscPhi1CxW1ihHgcsJMbZcoB3hvlWm6v1mj4M/nEUhfM5q5l6i58+Mg3PxkkqJhqIKvxX/a8Nd63qjkFnspsjB74hkMzVikrpiMPtG1a8/sITzjBz+dRoSL62DE3gDIECf6VfKwrsOJs5mEd/RqfSNwvP9Zgf9Adb9GAt6pEScL/6y7Ov7/aPY0aqHaHF7UGHh4+ikxAmlT5mZpK90A3ix/QPYlnJUuES7sbPR1uRmFD/WO0LqSAIOPn2PpccvJibFW2p1L31kUfIB0FUA5XYeleCeAqlfJ5BErSVECL13yxHSdDA5WvBHUfWN2qU5A1qeg7XBML9FyfCYOQcRvk4Ujnzu7Zvv3vAGse9hm/aXu+/i4zggW+n7u7hMg4LQiSDBwsIliOCK+xqHy1VMBlkjH7Rfk5dsgpWVZ3IqnBkyYim8AXpFcbz2lyMnVeya9CjubjR3QeGFNpiKNza7YHmZMdVpv89rxaVVQNFl1n94DH6c9nQuq4Yov/4TuKiPi0/ZlUh6K+0d1SFbZC/0ScHN50DSqwyklWtDG4TiWbAt++gwxa0tXAR3438/601/bAc+W1h3BMHT41G+MnyBnJrwH8s1raJhmXkmLzg8kDAYBxqk9jS2ccg08N3sD1fIis3kQXFACIyUGNn5Cwb0bpPxto8Jek=
        - secure: cNmfBTcAzu+7J9DRBBl/eeFXdqBQSAn9XcFV2Dq8WTOComhzlbG9zMS9W+UR0j2jAkP4S3x6WX2a1qnH2riV768kz0u3TtMUm6DPQgnvp+vA050sozfwITUeZ1sVsd8Y1T9DaHdNxjsoqPdVGFOqhvqZtjHmgJu3NggTIvmFDeRpSDQg/sg8HRM0twUG9opp8k1ygjPf9tZmcydKs7M2wwaiGn4TjMzDCIKxSuraM0uZZEAg9px+Gx7ij1Igh4w4wCkZEYblBr+LxbzD3jcHDbb094GXoFBgTgUxzwQRyz14PiXyWeu1CzDhxa1e+DARYsqLw7Fs9whbUdcVztE7jZPzj4ZQPF3xhKYezHfwMJoxR2Nkw7xDFiyIPNBprfGUVLbamfHzgEB5Y6h7xtz7vtfe50yVStb8di5UuuK79MX4pek05HpPodlHJ4ztIwY244F4mgd8Uvj8Hemc5rf8MHrh83iBpLL62cMtg02YdS7ZHhA4lywTzhwkprQ87k7fetQJNCA8EIFOtpQdbOqsS5UoldFLBN1ipgdiJweG/ys6YxcMErsFYWX7S3rI2plaeOf6TQ7Dh2uoCpYXVM0dNE1Ja9dEX2SwkeXkrfdY0HGdeUilSfWJcPeGHjNowPyYQqAb/UynzGQ9rW//XzwQWhBsBC1bK4CQLEhbI+5yZ7A=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: rByBU563gNj1BZg+Xv9sTONlkVNY1m3lZMxWb9yHkO+YRIwpL52Eqaz4eyUkZ0OG3earGc124iPnlYlTnit38ZySmwV1RnIBY+h2KoFU5drmyn+Tea2vgD8xJcAvfWOsmT4IHc8ByqmLqw5dJAk4qJo7RzbKbLcQKVfEoKLyUgZTzDLYWxohUno+bUAgOk7ElLE/4mVqNbT2dTs1s03tHl3OnbzkexDvZbZP317o+jJtUbTuFpzla2/L7EtyUEnlk4j9QpMgMKg9wALQW7+T4DKNbkSM3TdQLoJhCnOhLhaN6bwiVsRy0EhDsIIHcL9pBJY1CG4Nz6Eux/A0KS7SohhnQGFWXvp/Dq3o2OTOhOFkQf33xUDjWAD1bKDfBqtXYSO6RdQaP9ksiPIOWU7NaI4IPCr+Z/UoA4dysdHxXjfVQ7ikVKeVHlPglt1V3BYUIXqkV0kbqBTQn4TbauA/VcMi0eo0J79tTcDpTh1gRhOQCkf8Sl0/GXjD9znxRgDwyHtjKD4ayXOKnSpSB6+a2UDSnQ4pLFcX5t4Oats3A3txaXfgdD0Mno+sEIuEJtXiKWHDNrrcOsP0Cd1+TMO+0GpyBmLmQO3i99LqDUwaUuJEt8K9NrI708KyGBqeXz4uGoDeTk1nsxa43Zevocb0s0fWG6C+hC9s66ZiVn3cAW4=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
