jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: voCwkpxHs2q0CPO8MomfP8H9Tab2F1THasZNDGOFX/N8DtJwMHXWh1haLt+uz2x6R7BVAlS+IE87DPCsIqzMYgajJK5tR4/dPAUTSRe9V5xt3yjpfqJyTW887jm8jA/NhTYp2U7fyydAdxXLDz+hVdGlqFvqsmns0qqQeP8k1BacIcNDUwW89btDDXHWRylcVQ603X5uWuaY7tHx/TEH2wnM4u+DZ+vOotY41eHkEPOIbVTp66YXe2iiWm+3x4e+2H2SA8HLPbTjyX7uKILZKnv5DhuM/RMvzn5pq+YXmHF/5qraS7sEMKK+mCezMjPQiHVS0TwXfPBgGyBDkVdX9Upzu07lentImdhHliht/2xMT5dKlIgxInF/N4uog+jfNdRXi1SU2LNWqO99OcfJuFy9/theqWvGRBjq+yOLZquOBroMgkWK3OyiwPRcQwKo7+JDY4iYNJLpAmJP8dBCwwsxA/k+/hzmCTSIajzaY76UVVTmfFY12nJqAIQ1fOi6+4EmzEPNvoMFI+QhjIS9rqiWjxF/EE3kuXmz3SJ5ATbTlVnxTJfm1gfSYVpwyjcz0KtHQP3Z7GmTAMEvoYYxnl+U4Pi589AzG6wUdUFpPWc07mTPKCDUF0OjQbLgu30RzP6oIucpCi3vj31qEy4Qy2mfBsxnUWqkAUGbzHjS4vU=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: BIWAq4fLWBBY+OR5L6JexCi2/P6bPmHmsAmUpNxXj0f6oqzIv/khw9y2A0E0lDLTc2qgZh4BFZ8cdAKBVYo6E18AJAgcEWe7Td2CbMdgFoVqrPlBmQH9yyPG2ctJTR3wA6TKa/RydFGN289G+ug2NX0ZnrQwhF9ksM4M4wPZtBc/bpxuw1gVA8U+uMBIIwyymnsfeKIMuROUGNqv3r4fFu803/nBlMfkiS1CYcJbzYrgeF/dcf3YH1/cGzbaCfR2DgM+xIGSbAyKMZI19f1FlQwncKJ/X0W0Z7WIi8MV73qJZLfRdE2uB7dvV9s230Sawzx37EgevK07YKXRf1xoBPwm3i2CyL/yCxtxlj7VytAbpnqcnBpY6UelH2zXjNF8pnh9clQTaCCjQ7bfM865wcoRTHeeRrV4jIgOFa+qvgBBhRkcX2u7aROHXrhfx+lY9TCbQutV56SgRjjTXTU2oTlYX94nd4YDVIczAa3pZm/U0k5pRR1JmIyg1+g+s25OaoUFrThgwoCeG7g7zx0I4GoPVy+REUWISErHiyromviEWWJT67z6E6LEkXpNe8bpyxGHeLd8mZI8S0r6Unj5foegjZbc3cMRNPUCOsxyMHiDKtxK1H2cKSw0DBbsQCKkqaBHr3Y602GD8NlxvMOngw52a+6HmUMx9W7sAyC+nOk=
        - secure: PZ5luYzkSUktnstQwMIlV17NhuttpS3cgee9Bbl9P0VBaRqxBD4ERB1wuQLpxzSCaLRBHE8RlSKk4MMLReAO+gPCokAIpaKaX/gBL4FUo8eQle0t+OWoQ6kgcBfoQUUAgbcK5k5B5Y7lrJtZoMXRJiPkswaar5Bt/Cq8cYxhK7hGsEhihvOHsThnuUZqHsdpwcfFt4SNHbGx34yWvYH4vZMhMV27UcYt1zgVGM0ofl3frVhkPp9Kvv6B0LZBmqgIJ11/XwbhNvNvgT0LcXfSZwX6kqLt9ufmQQreXhUt1pNPAj286wn7R2hjBFFzfs+3RRVOC9FRsFAqm5VkFdr7bgtrwKWpFhSEUWH17HxWKRzOw8MY7Rz5BY7uuR8sh/5aBp4le7aTP0N/sUzNtimw4KJL/VuvegSAA/Fo3bN+sWDR/CLVtqJtB3SGUYc6r934Dzb71Uo04hkVKmV1tF2gUUrrddM2BPW9vJpXCNE89saxyNGLpQe11cwU1U4iuuYJ3EUUH6mqllzOQdnRXusddBU5O8sgobArj9Sa0wrpl04vMIECCrNli1HoKw0orz2tlYwdWhyk1Ocx6j1CYXHFRWOWinXNAn/DQoJ3B1aFgG38f5zCj0ULpKKFEo/R8kZG20Q8guApn92740kJFwXTTFDGh23mwBGku1GEP5RYTpY=
        - secure: r8mprYbHUn9c08iq+PHTq+ngR9W/xt/sHSumVAVM5F4VRfBuvBqQrapUv6bdE19NwykcPB+EjT7caCjJ3IH10vDWEbFlXdJD8yOfoKrQ1sEJyWC3zii41k0D2pCg4fVnNNgZ1+Z70lHYE0FSd66eh7xdbAlN/lZVM7yGlmMltTCKTNdzM9hvYN1Don//ep7wRzdu6AWLCZI49aOVgRWFZskAxdmUWOnQJoN32YMZZEUQtLd2kLcuqjbwQHTW8yJJuK2tteRFQ3Rc9pCU5NtACUo6P8+nTsaEedhKxqtOAU852cmFMYSaUj5to/MNbx/hCblajgxcb+l0lxew3/Q5ORMkB0K7qgyypuOBzIdxNO+SZjRcf1Wr0raYkCSmkSPi1gpsUu3ZzOLiNtYdY2h0yPnJ+sMGhgLCAEIKQcb0pRwg2KCn+iDOBEJ/3mujTAWPV+SOudQ6KXGvZbd3czTXaUo2bVohoC3E1+xtzbZvyF2beWK93oAHeNvN85LgG790QDFzlJ3TdUlqSyuJvbuWKyDyQJCGQd4zOw5PsWEgWVw+IbyuSbjPTj2bLF1gEZyFA/vRA27v7r56EqYi5jmPFrm8q8dXVC8bpwQQwCAPIwCLxu4K5AnFLjLr/NLZnE4WOjZoYF4Cxfi8JTMXxr1C5l11Q9J+3jPTwr1nbdsqWAk=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: McLNQcUvHLqtGK7RAiAHlLjrNauO++0tgwHkBA3Rd5A/FqZ033AY0HqIIxOaCfaRSw7x1iJEnHnc9LfHlJCEghLUpzocJduyfi7aWTKBwnybVswOTvVhegdeVgHt3znK6MU22k47brkEwHmMLOElK47D2VMKOpOgurHAONaUcDnn9E/BokbyMqgS0UvfmXPRKj/IaEIM2JYHDCz69hoCPJoQ1xOJ/F27APiDPsfNSCidJzCu9/27aXh/dXXC2Of6BeTe2eAw+YETUXCIXBhSH5E2sv1Tv7cP5mso0luXGhPYkaQhYFFvOqNnamGDIUZBwCfb6frlbYaOUGqvMTgyVPSigPgRlwaHFIj22P7KVnhZfRJcaC8ho+sdNJA0DgCdEh0GroWLAgu+NTwviT9j/+f1EjP5JAhIgawXVuBdJjJO8ybELB9A/0rHAyCSzCgABUOo8Y27milT+yHNDj5i/8oTfRVvVoDyyP2hIF1l/04ZTejUyrvdqs9UaA6T9zwc1vq+U09CxRn2k9YPhk9HErXYSZSp3pnuQOB/jAlm3teG20CVp71DEW3Yuu1vQDu9BvcbUrMAungVJWcCS5Z0ESVxbiHX1q7sV79hImqHKUJXiIiIEI8hNwxS+0vAo9yPEMB5bEY2CsAjmiGzstkDuqt+ZYHESbbdevFaBzRNi8A=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
