jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: hglltqteeKVVFxsLX4YX0nQzhyNNDb2SZgmMr+lDlmSBfPGHbv+LhVe+GOqJv4D1w3qY29vJbaF+PPp4R12WmU8pulAt8EHHPehg3l8aVg/6DAEkZJhU0zZ9IgQcbiZ1zcoJcwPnVvxCgnetxtnMpv1Vgc1v+iI3BCe6Rg/PI1lnQNm1XyabWEtkHM3Me/aYdV96p+crWt/y9TCZ7OyJ21RckPqCBKxGuPPr3d24Pd4Br+ecn5j6TdKK0S12JrJ+faGNecWQJaCqafaXzO84IxkzNrpy6tpeaO8PMJi7Rm6SqiFAXdz30/hI5f1ShLslbGoL8VllZJsQewNFbGFF8ig9891u1vQpdTRbqvej0xMxA9pP6NMVOtzY6G/KrhsoomcxaN6SiTISohtDzQxiYQxbbnoV/KORob4nXmi7dCXcv0tpazGlN+UhwDHEhwnLoTPupnSQOhBJRgN9rsvsHsYSWS2c5E77Pv4Pj2w2QuWCYXflQwjR1Ax7d3yiCUkAljns4bZTNWU8vK6qsBoZj5LE2S2jzsm0CjU3eGakOLIy5r8u7QiOKuYCWzTSONMSTnQzFDoKbMPOikoVJ7cgJNSvrDV7/ECMos49GRkx4BovajjHhiP+H/Gz4OdSEaJJoTFYzaQT4MuktAhlPmh6/W4idwPJd7MnoPYL7mLMa6o=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: He7WtRhzy4kIRnrAFvB99xNPAdHAioO8R6Jsqr2WK6tY6WVcajpOB/f6xyFw4vZ9rns+CSI1EFLCvwND3ffLTslrusLu7YBCajYHuE1mTcjCihRDskoKm9TspEyCGjQ6JDuB1xOa4hYrq3WKJu2DRIvBW9bXN2bv99uZza2utXhDJmmK9N+88xEe9dEOzUEe8B6K8PD8udT8gXzyq/E9Ux5GaYFfIOd2ZzdNJ8N5cFY4nGPSXWIxgOdz6xyaWYvCkkdn5g7r0cNJ7Be5WyIoGrldDXRUg68oYDSHFluuqEzNqk5qV8D1kiaZ5Xep6tOMZOD0Fw6VyIkPmQ5DGOOuZiNwp20u34eBuW7MlFec0VivqGWIIVtpxhncsRbW/dX3LVqlRrZiz8SpDXhzCJnPb108gMeqVvuPIEZfi3mFbCQvYhwf4cu2WVld88KofvzUoJKCMkX5h8XM8B2a0684SuRVwKag2P3WdQrMQCnY+cU9jqbQJ7O39v0nIhBy/J5052N4IoGIyiQ7euI3ZZMKq4wITytHPnzzbZXJjz3lPohzvzs3hxhptc8mRty7hRTud/Ghb6brCRg4ABebmzLQjN504NgE2gR55ClxHzUpfspR8cZp8GElpeFO8LbVUvFiarCzzUglBm9qaFM88RUndZ/aoOzIWK1Tu05iJ9Ga0eE=
        - secure: Jqs7td8/RD9uJpVqcWsGc42scrByTURKEoYwLv1LveAJ2gANqrYPzv+sbEGN4CMPu/G2IxStqps/isByuRvdgpRvU1d2ikMNlTF51MN678TZL3/lBFtBj9S2mgwQ6bL91wIQfKsdRNggjxF71+4ZE7dru3BvnqboFm7HiJStNClanhDFMlK7PCIi3Q8lMKrHzJlQz5KoXMTH0gXjs4g2YTqlLUH2nvJcpihYzQSYApby/PDsEpWfqxtnRikeS0v9BULIutzJ4EQ4xTdxWemg7+y9P9AmXr9PKNWDeyTOyjsqAFRm49qJxxwP1QrNNL4cY8DCj2+pKfVfONp56N+fiId9MJYP/dQjGCBBQdFLoHhVQwE+9JB4prXxtLEdB6oJf23ipujUz30RQaOvCsN2FbkMwAj8sIGueF+8z/rSRhZiAtehb2MVQMBVwXb7ZlVsuGwExjIjqpqZu2xyluWwXSRvOrVL+efA/ePiAmhyNz/elfEl2jY78lLQrvJBOTBofVYPiE96GkgFbaFOABi0RZ4FQVBK0rrJEFiUHbHd7F7VTn/p1W+UtSAjZ6wSkDt/tkPS0yVrKtUcNVjqMWCavPw5G8GC852z9kqcFJsuRN0lu6kae4lpOA1UjExRYmVdxm3uyxM6NLw7MAwyioedV3w3Sl5IMy++pb/SsVPNkUU=
        - secure: Nw3IiLXvIRBlei5WrcnqX+oNWg/mlHuu+AxODFUEi69dRq0XOqCx/ozd3VQ0YUQ/zzfRlGWQhT21Nrdx30bhW2dzuYgbG9ALiSbFHn1Lgl6feKtkR6zxki8SmvwCkdelFU5GQYdpw+0zlMsDL/9ymKyQgsQI8XomWUBIBj+M6qS93drcp0yN/ODEyTNAfoXEfZwfeNPPIQN9XUzvN1FMqVPJb75DHB080MBax+DVcTLUvmzSvsfLt3LGx92IIVhLoK1VaCvSbgFZV0gHtQd5ULRDK0vd9+cT8fpObhle2MSoti/St8R1TpODnpmqWMd88DSRfO/Zjru9emg/E2TP7xjNCvES0xl4/3eNY/RxkMOfrBh4ueF1TMxp5/cQ45UDFMXB/FJY4kzavI6v2NWyo65mlnA6wv9ceAl7s+Mr2wSvTIheNZG3Vu2eGI7R83EmbhaxuBBjEjGNN/3ktItsWLcWXDBF+q4DYHidT8aR6okIon4gLrKjVesgGMDGJKVrUiQkMeALkupoq+kQR4YwbUif6VOazddFovlPItXzxsLwiyzgOaKnIGjrvrYzN8d5WWc5wro0jI2xavSwvZeM6cqPPIqj+YEP7eUx9lYn4jW+BlEJG1+qaJl1Bapw8HyFdBBHk8zj3tI0iVu/3x0+Ldd/n4PxX8WDQJvKdyTC5D8=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: KD1W0+l8gYAcXjTZe6oG2pS8rEC+U4dX4BfxZ7ebUZxljMtIdOHoGpggE48cWBqW1/CAplPeUVPeX3FPX0cAYU/g1boWBO7PY4zq85XrS5n6D0dw4DVXRBVizgpHjqM9R64mabMMHaJvgkUBm8alVOPqxHEYvG3fDg+tdIVBi6BjHcqBuP2vsN421FxAm2xnKm5u3mKssi9y04+BLsEc8iYXokinKiV3+P8R2NUaX5o9zPnQjOw49tYt5/4NiJJ30Ww6EpLnY4Da+W5nZh12XRqaC992ob5PTZ7dyzyzSnBGP0K7E7HIMxRVDwUhZAzfddGarV0ipMBB3CLpHA//hkSR3mlDgafLDwf9/RuJcf+VPHxNB6ZD8Fg307NubBHGeBmJfZXKMPPGnZr/3ufwit8d/INFvX/tTkIazNQSpHmBnezyrWWIxxdQUEtcyPyDzxhbY250F6Q+nZ5q3rjqinbwU7x1bJjupDvzmF9Og7p7DLFapBqJFE4/hB0R3UUBOhkKAhRDXpmmogZhjZ8p8Ah16892Vt1ZqYZ31Kn8wUkZydutzDdTpBFjpvlmP0UcGqr8cVrfDmBOdzg3k9tmt1B93QzWcSilIEp4dANuJIlrpkRbzrd117PNOwuwJeIOQePzkptf92RrQou/+Ha8a8xTGT81pJF0/Pw487pPW1M=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
