jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: JZy8Q6JD5ls3VTo7l5ULvDnRAEVnWcICMaMNSuxMgbSs1HdfxEvASaM8xLMzwlcqwR57K/wfM7Q1l4EySS2m7+aZaA5vSCHFgz7oqOSlpqhnKvFhPNetnfUXqL4ygh1nuk0D/KJokaUfCSKM48v2+fIbYnGmf9/rsi5TG1mxGPq26Zo2+NKT/2GuFXQdlEGPndRBNumai4Y2RfzOOLjyB4ggWnKKkQkkgwr2taekSybhVVK03XcP/nb17lAqO35mG/og5rKMjPJIQ/mBN/R5LyND8y3eg9MkqpBXiAKYv7bw38vrxgu5U66LUEp39rsNkT43JqZSg7WmrL2QLTophsPsYkKAGMzJjtV2hsajTuNUMCY7tsRXp39OMcYR/PwDZBXO4v5+L3tckeEmDUNULm4NhFDHJRQoE2omHcw6snyPKaubWAxh15O8VXeuSHmOHfrE6RuZ2mg3KpVODtd+qp+Q/7SIC2GLPCaQxDniPke+hpwMIGIqHu8LM9MOyZ7Qsi5Tn4OvYR7QjzdptQBrLSXlhAA4SCKAobSj29D49Mm8PIbGuVIAWUr4RCzLGsFZPkJhuXI2NG+QpeilNMxmigQMxe5RBL3DzqGfuCbTmYKzuxqCErhP6xbt9Q8Hm4rEyyCrEi7aa+ITDsONhV3a/+DEeqcIy7fKTH/X4YTeY5I=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: Cq9rllVOHrzZDHjcRrOZ6R+QUWc073TmdP0feua7DbBHcbU1gGdTOtGc2u6/eviRpoPLsZhEAv4118cIVxhc+uyDcjvSkDiN0OCLNVmSAHnHc0JLY8kD+KePExtTmeA7fZjD4+StBMXTHVsH9U7DFTVlO9GrWTHRrknRyZhgNyqfszwNYVgu50mOvJWxR0ZJ/BXs26FqU9vPc9nFYTpRVX1T0+/bWNWINMTyHcpcUf8e/c73nCw5lqIU68uvCHld+79gmIjjBSAJpIqGUgr/Mfdgc1hD/2OM1/uWaLPmu+cXQEhcYJCHWLp2Ga1Nt8e3yBERTBteF/neAbjHt/2KvxBCgpdzIT/QKtsI+6ypsEoPUjApQ3PV+uqpJWhCxOwlQL+Qto7foQYyvTvSKDoH1aly70AI6Kx+qDTDq7fsg2wj1sAL5bKyF2DxXZjJ3yGPWBRjyjiI+Rb03aH7IMiO8+9bqU9Losnbri/Nz7uyFSIxpBTWj5L+GjVzug5Okt+F+Tp3pj+TKBSA6rnDALM0Flvmls1EZRcG7Ypqlo5EE2s4UCRax4l8+Ew0iSLM2h18KJ6XKS5FHhzVXyvd5Wi5vORevXg+Ug8WW7p5O/Bufp9kFilzUGBGBnG8vopZGaKu/FxuwfFsI/d7OUWfAaOFej5BxdWUd5bClbIDCLpnpYo=
        - secure: Na/39zJsWf4A6g+lcdkFDufOWWBZNalNuYOy3nN2WT4tlzK5JUfIzTvT4nbdYbADiZkzT+6JB6csy1c4Qai8k9T9X9F/TUB8I+WDLXywzrdp0Ef6VPe+0xnBwDATqvaCD8kYT2aEGKN9KPKyqk4VzoneFTQ6TQ5XWg9R61HjrzuqAys0pOQ7gKKxOY4uvC2w3CY6OAD6pG2mSNyZgGU9OcCVMtKckbHjq+5REt5se9yMfvpshiEbEE5av2macAsQlUoRpLTRfy7vEqeu4jiuC0HODbLknYipJ+iH0tmStMDWq7XKmM9XO3NfR/G9y4cJ+dGu2B8kI6lS6BZljdzLSUn1Gp6Z8oxHVW7giq7FTDrTWMuLeqsSK2jmzgtbaDBcRMbuV04UZGuNq71LFjpribzSHa8CdtCBtaJJtYOULBdxm4PhKKj2HciBpqkSaXfXFpQ8rYm8fVzm9H7wswCpQq6l9w4CIYUr2pbm69iMRTT7GVosIWYKSfvyU+bbOPWPvKEqrrt322ahea38eVO4rwgBGogGNdTaePB9Urm/IuXMUQ1jHTEZLW3SP5w3/2ffyGlrI6yKc/ANvg9wbL3CTl3oP+UbVfH3BHCjrvntmQxoGyflVY9RkEaFJgU5Nr1YxbTzwucNZK42gKtDME6GcUPA2dcCqOQsPYxQnnbPLGA=
        - secure: DqenA/ZvE5nYk2Uqn6J79ewXsOia1uSc2kmB/yaT8D2nNPy9n2neyg6clalPD4yW8g1XaACqMb/EwFd8YwosKNlqp78IVQAH938fZ6ELoa1uj4C/Zt85VHH85DneMzjcZLtIF4x/Qz8sWD0UxiOMyST2FVC61patumIoe6/ZSRReAGqJdU2b0iBNRd9JaCucxGwwgkgT0cQVVz2mBeP8UkjBwddoY84+t7tCQdWb4OC+i7iu29Z7h6wPyNIsSAOBlhoTnQrk0kg6N7vJPMNVI0SNZQ6T9ro1CFsT+PwCTPvvKmSIBiC875kjiCoMBf+GPV5zmrIXNwsV94a+NGLV8ZF9kXpKWme+xN94AB/y2zeZPpYpmKj2unb86POgh2j+PywY3krTOdJ2qWFwmVx88LtOXN/m3HkAFld9Ax1YXj0ZTsbNdPjdzPBplJ1lKcKGyuvcL6dyWgilwMh7WoyYB4UTG7uhsi9Z6YyrXIqUiQvtiCMm8S/8eVV1mkxtrfT4EozzZjAKFx7gJxByr8UFODlFfEC/5LgUuZtb60F1Bev5HXKEiAsDBbYnAxWNj1i5KtF1tyeNTW64Tsl3/yZpidtH8m/OikGUepIqf80eZmrONVTgNW5dItvl3MS4aku18MboGGDJqWEZOiPHhSMW+zW5vc+ZdDWFcCZwsVillNI=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: b6X5XylZ6i8/9sHcahvUP6GmjHFQZUJwTtGQnUc+dSfUpEpXc74ZKYoFxt4cwVoTy1na7sd2e+AKEqtw4HW5IuSCHQiSIMNXn+cQoqVqf283Vnf2npFWSe29deSmFiHcO1EUWKZBVKff9WL/wEOnBsJEXg8NV0KlYl9u40w6HoivHecCaNQS+f+/4JPtjItsgcqsbtMINWi+JIkRWijAa78PMoRomhM5cLedAvX5uwBvIivUUSIO7qtg79REabTWUGcnfp/D8tb/jZuS6OvXLHS5tORSbD3CgA6vz4Wo1HPLjAlH/5/Y/25mnQQQpanGgrr26IAMOWhgiZQj2sA3TUuZwhe2AdEylzlZR1b2Som0NxcowpoHan0HuwS7L5zpDUeJQqehxSSmCDIBKKewVGhvNl3263C8qwqakoAPGYe4UsZi+z35Wu8EjKfe8QqTGVffZZu8PN/DCTrFQJQUjFokaiPJS+ILGrMQ+BU9jCUGgeo0ZJUP3gEC81npWIY/tRij8a/LN7fPCdo2TttKKZAuH+nH6x32p42VPMM6vi/2xJBKIvwHXVap5fN5yUj8lh+CffJyxxNgVLQ+PDY2sdXpzFwvaJfpqodnccQWpz4XX7dJZ/GsW7lnkfh95/wT8EI/gjvIypkXigRnlDo8FLTDDATtQPU5mN3Td53zt8s=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
