jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: ZmcxVARLX7MSWifepOtkNLvV16+X5Pr4dglEV+6RMnxg/IOSNNdqrU+UrBKJcnMApsS2J6z61o5o9n+kz16P59dMiqj827S7N5iS8MHmJgaolDjU3TfFWClkExGP11Yw6X/nwEBGT7LLLex49lbdlZTUhvz0kSn9pNIMFFKqEERS2OAhqV0MPV7CxYiI/2+YAsOeHaxIXvrtArTEbooZ04zWDE4DjdN4456RcHWwGPrHKcutw6G61syItra0UTWS+zZK9hHfkTi18YTwIfzSXCiP/EtHbFQY/8FowqyDqyzOaH0ArqW08+/EW9GSPLdLONjjUA6E9dr4+yfGm5QYLef/E0VQqdWTtRBjrEa+C7zlDz9ifrYEdmf5bsTlvSCjFXOs0EmM1TCIsMDz8TFK0qJb4mkkX4HckCUUsyIoMVHLyCgeKcVZrUBfgpXFltmEh/thhbDdb/IQLU/mieeUTy3B/TFDa6JkRr95eqo07DkNhfAqGEESit1SMMQK7E5ovLCSgZx15jLzNiGYUktO+QAszDsCSobXlXoE1dV4IPIoro6d93JURKr+wUoJG/tbgkzHXuF+QIPKeeC6hpNKFVoTLR3KCZHiHaedDFQkLHOOsAT0ghocJg3hogiDcKzDlakMyyY8szEDynUt76Wa4ZJn2ok2HkQ7BZH4bxbzeDE=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: H2kpbUgdzeVf5USOWfHrnGEEwGdkW3G5/RSZY1nnHDA3l7znhWd7BFvk/IaPIZPbBehwPU5mDdapL1oZUiEwKIPNi4AGuLvkOQvv7NOYIkQpuxO5a/8fxfI3sCzguDKKCMnrNEHIplseuRUZH6ALhnVNqe8MK6NGnfr9BbrPc2gpu+8eaozK+EpmvrQO53gP8PqOdInSl1sHMNaPUqN4rAm7ZecjdzTA0Xh1CC98yUHORjgiN3QcO8V3zKsEDWNk8bAWVc3KGc5WiG5x1i7OF5rWlC1ivPh5ZlNKkRgTI49jOkiOYA3g3C7ZxP4HQZxFcLxxCjMHFJP3Lm2km0BEAZGAGsEU45+l8jIk2Ll4Op5TWxdNOHlYqzJRaxMkdsVDzTKYHfA38edPVs5WvAaqkyIEeKcG6tT1sTSDJ7CxHmlHaSb/8OIIrRdgSB9M+XvgVUnD7qGIGaFZaAYz9/WuKpCdVD6WkQalw8PC5D8lW4M8h3jzNZb1E1lnzChhg1cHugfVv+O45UUlNAxlY33XyBMBup9QrX3iUbrAQp1SlAjs0xULSfII215SOtVUwXhQO6qf8lnFrrv0YlK0Iulevlj+JdJ8ifC5qQ2zaUiFUjXsBf6dq1Cs9CDzkrIK/5Ql5mIYzFdwx5HulLrt44Pz/pSm9+2WolMP87B1QTP1KKs=
        - secure: H2KLdCkaO5VRCPB3yJFDn/FRCEavXnHLSkMNGL0uUIbAGUZEhJbYShck5K3UURGN6wJ53l7QFy2zK92QiogsgpCrIhOD3LCaRvifBYGKSkxPXJmWV92iMW+bKW34OctMML4hL9/aQZzEUy2TlfTjSfMTEN6cQMlWN9oJfTbqbiO6xcxiKbu4wjo0poTs/NdpGdt3nyPm69PlY/enndpdv+/MWgEk/qs1P6jogfVd+bD+5E4agfsuD2kiDMjHJGkp8fNs0osZWod85hX5yPMu/PoqDwvkDM+2LVXmAiyO0Xs/sXyOfvNq75ld9PfaAqYWm7AVHlbioHvifcfTjWlGnX/BR7xRl8ElG60P1aV6oe8COOO3OyiInUiEc0Rh2JhJI7lkM3Hj72+ENGXupwSjbUT6Gz0rVrXFY4evYxNhX26QBfribkL/HkkY9dp4dNZ/4LAMDTTTGqZ3M2BtJzsnfibnFRT1KSYvAmHyEu+pWa4rZgKoxw1/o7r1sX3EtVLsrMA1WQ8uTYygppBV55KSc1ApuaIyXEGmf9MoyEYZ4lYmrN8HI0hPRoD9/zWWTXWzx26UBG/OU22qYmp8yrrSOWwTm8GZpQiTZBR9bvouZ+FfTtIrs0i+xzz0ZpC+neU9oeKAQS8k/Q2szpH/bi8w/H5JoI+9cpFAILiV5+G2jFQ=
        - secure: ey0sSmHSKIl6JhbcI68D+EQ43dB4jwrkY0WtgG2f7Bs1KGz+DFlTgRUYHIgu1j4pdynAkW9VC/QwwPrs9n3v1O0DENxUMzeDlsygArvymZyTmHEUSiyTrPz/D2Ct8VYmbmSc9idY/fTy6gf1bfpFanw9gqRVGCrlNHZ2ooxZFEfkFoNpOlaoym+znjPvX5aQ7o+hU5TSl1OlbUIZ7hMrAJlX8v8BjYY4baWYv7Z92rh3zyk7NgvszBYsyBwFf4x4fToJrmFtbMtlvBPPfktVLU3Ud0flcM3D2KqQGOQiew6fzldaeBDTEWaXYoLDZhz13mUdhy36joVksq0WS6G5RmUARBTi/wzU88X6+N00q43cno1PFdjsV8k2uJfaSYoKgDTQUtmVoY5Y3y9KeF7KQ0/gdXR46kMYAoHvsb1EnS+TaLOkrKio0ERbfPD9MC3ntfLWIJOehjl4Y1LxwdPWY6xzagiYkALoGaBkztGVWM2WPebavNa4+tXAAkhjw1/4tKPAReG/fUS47ryk76il8iROpHqEE56qX1wLKcubVQe4dt2fhmvlQXWUb4VeXmzkbHMyO3YoMO4C2JqJ4hfla4Xtg05V96LLPMj/j/Reex7ei4y5DeBVNV5gjXdQ3JkJQAgbb4MIo4lrmO5VS71/u/6q/HHC3n89hVitj952oLY=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: EZ84sCkvRXAg5oJcE2mlk1C0nONZRk08L1s1i1gYD4uDJxfl4pzttFfnN0RSyRhakvqtDEuOvMqetRd/0Dh4Ine3D6IOpGqKpCt4H+IXZeIB0DqE6TqTr+yiA7S79A1KC9PG/OO8bV33h+Yl9Nn8uVtiTlO82yZ9DmCtoyADIfdGApO6NkRAlPjyJAkpXElSoyHFzGaKzysOaImGig3G+7DWdzI2phP5bIoOgTIOUJCD9ACaDGYJjOlYVBu3Luoud6dt0S7GztkN5aIegT1F1DkjpPFC1RJu6s2nWUxtpYbLt0sGo4/wt0SE9xOtMa6ehNc6jG2RPA0vvgLxasBJkDPZdA8sNT0ndKNQHim/tuwrjVKyH/yl2yB9EmqvMtDu3ynEzGCNgpz97uMMwYFOaBO9oxyUn28n3ZncHU/w/NP0z7G3QIofPt2oHehX8ccixNmIdjSb2dRGfMRTtM1Ho8xSW1zcFEqeMXda4iU/xU9WDWMdyBXh/BhST5JOUz7N9obOfToItvjH0++kSRqwnBVSw/5xH3nWL5JwertyrK75g0MeodqXMSjKks72iJOgyLmobNUoUiqua1z5OjY3Qa0fJIcqY8j0IBO96JhMPGQ92uQsZUPxWy3P1pG/xm3QSRN2woV03PSPVr4Uiz06oECoQc8n74F0LDGsJHiTWTU=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always