jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: TbzlQzqApE3awPRQ6y7Xoq7gimutIFJoaDz0iiS7hOxMbdKQ7bHg9iMVysLVdRW32zzT9BhTcxOZdTiyiZ0PP7cIv4p8larI7t6ojTYSzUnjeQigVCEk/M/9jtMQpUX6bnWViQpEG7/2MVMzi25LSsBda4HGA/6rk3xbE0eJPolIUoomIx2JWBGhcuc2G+TVSI1NzLCAd+BZEkuyGSHW9zq/ovB7nlwZY1VECcn2A8IB3K/uVytAB6vc0gMc2m4LOmc9Ov0SFtRym3V8sgcPPNjbb4LaxsI2Yjj8OO9wigUE2EycncHU57IJ6mt3b73TCqJJnW5l0kGy48ZtDKWIMZZTZngyhNkvTEYB1aO7mDnbmDFpeSre/UkKPcHOUj+aydQW7qt5EUT8JNxKkQNpcEfCP/oY2YyHa1kMlu6BwIQjPjOTDy+j/qCC+LCpehojMwtiPrL8Dm3C4SDfVQ5fJhM3VwPFQhbji4+PcIeuLgGqlVCLVqZXZKrDTk72URjOPqcEQOwYNNQJUCp2SsygN8a3N+sE9PR1A2znIT5TK8zbP2WCU3XY0mGxZ5m3NOsMwJuKa1mjqKXs0zxou6Osoy7X3S91EvFg/boA0o8re0IHQKc7aEnNf6Almto8TmS+mwYDjE6Df+bF3CM2gxJAOAMK4RkoDB7r2WcBQ9vIdmg=
    - stage: "Deploy"
      if: tag IS present
      script: python scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: hq5g+IjqIorqPy9MjwA4s32/tB0YR+Hk5e1N4C8kSvcoQ+H7yvxn4/NtSEsd8WEtL9tdP8nGIiK5dkgcEp6zv+/lIoBdEpxVQFD7AEmHnMjG8iSwI90izcxCUUxw0vSCaKG6BI/7xjmS5tr2DigU73ol2H1tM3pN/B9TaDTbWZFxa5T5kMZnaRNdY0SRHlXt8JgnpqmBrxTTpo3pXrYgrJb5AGgXxLdLqKrZXugy9EW7wMDhDrOKiVMscj9ojwn9tSx2pDytFcbRCSI67Xi5cDW4tvbnl8XouBLS1sWWRJbfz/bjuRXhkh0bd1lIfK5/OKjRNwQFq/o5kwP8ZAhcBoPuQOVYVyKkDrUmeTaioTQyybB3RKA/ufyv8fgSoi833goZ7USkhgKMYQZIxG/3kobw2yhVBidgku+1MtP/PQI4Xt3cdK6q6EUUim6dVbrVeWxIonvazTQdMrtGPO5piZxrBpqOqJxQ3FezWP2d1oBh5EA9f58jjxYiQOqaQLk3yCWJddoqMpSDx7LLuUcp4m6M5LiJC7UMXfOqNgDn1JBG9FtSx1dWiLuK8ThT/DxoZCpxatcVC3oib9SVYloyKSEyZWTr7Lz4ePfbttNBWpy8rsryQoWR9ig+kWy9GcksJtv8tkQjKkZ9D/agKgWkbF8m0+pNgwmEh4tctwYk4XI=
        - secure: RSNuKuJbIIVLcJR/J2F+2bGTK37qHBUHnujHGVLjCStojNk+OuNCugU7BXdSVWPfTGziZGBRw0MWZTrz7XimDfsxcaPRWGoP7KzC5x1pbG7jb+49KeEYF1FZnWlrosLN4rUcJtXymLiC9CV0QkBl0HRCpT34uYS+3K4XjNN6qwm28IzNqjEqqcHdlI4BSeIkfXs3bjMP8TqGyhTXT9n1juwYntR2beTtOTpBMXAzDtNx0ZUMlAFaqfy4EuAY6FL8EB0c+L7g7z2iG/HqTihTqz6Rx3SdhDOf142S0vRFx6DgDqB6wqcbTcE60Sn0yOCnNd2Kmzqoqu17jAi3rA+rWfyMy1xWpvl18N3G2wSe0c0dq8LMAXkbS3dwboL+9sBX3rAsca+JiRQyb3w5Pgzbbwiew69aW7SuzqObkpx9u8LkyhSdmSrA4yiIrG9qqHcMvTdX/JUKmbxX4gWYkVcAqNzsjyePTRXKvPez1zSFTUVGNSnrOunyKM/leQO3XVKa7kErj9AEOewVGNs7E8HH7Fjd9ILqv/0dAeFratH/NkN2BZXcdDLJ8GuKxCS09v+Km6gfK3VSTS54DlfMKA42Z5X70QzirWebsW2FegteOmUW7xnutpcEgReiWWmapvSiOqKp6JTbY6uxuNUTROcITJPOfccnuRVgIqV28gjlGas=
        - secure: EPE3h+fzhjaMxvsfB/n8ztUxya1AvpmsWEBC6/nU6MhkZrHigSouSCW9H4MHHOGU5A+O0tM/RaoSvKB21ngEff5ScxevdM1Zh5VdF1tLQlbC2l+lok3IoqXJqrM+/GZ8Z9qu8CnoVbieNV/zMX3hks4A4OwW7YE3/rwAF/Bzi4iWISa23+GXFRyB/FHAmxGbqRqCxOtoMLdgnqOuzH48XLhKJmhtNokANVnJHXR678fo16QXRzQeg1Dxpt0V9feptAWJfAkLFI8bck6XgZEGWuq6NcgH+QNttiX5KimXmwb+wsVQUzJZ+9PJtBcM9ijskz7hrZauW6LFQOiABKAZ7iN9rA8R9VbmMx7y82Vtw3pI/XiwVlLr+nUY/IbsGsBtjA147mGVJvEsdsv14tXsJaQ//rV9svWbfrfJSF14xsm+k2oz/v19CylWccEiq6baJWU6Z/uXgig0JDUxSUcu90nAhIYvEU6DVp6ZBNo3pywjnVnxsUBNe1QzizylsygBmresFlh5iSwRYCvJBHg5u254tsEpD+pGNUwpMfTpqZ9yzGSbl82wVSF50yeZO/fTIGIInjfGBUYYZN1kcM/oiSgwFLNr6OsxgxZZIrIiWD/JezaHqwHuMGR8KbKo9oMNq9y+mYVKrVyX6jOi/sB4szElhUrbW5ZEVg3YHj8tYOI=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: iuGukv+4Ls1+a5HfVTF0PxdxEsQ+L4+Csn7YTjPaxYBj4Ut1+2GWXYq4BQkZ8A16UF4h2ibD8t6kHRL5VK6UW8u4M2aF8E2ezuNNhATXbYAoKdNPtn+cqCR7YMC+qt/1V4Lho47PWuGrvVm8ZBHU0Jc9oXF+XAyc87ojATUha3TpbC5Pl+1ZbSpwN081CfRlvBFoEoCJxikKyjdAnSUfoqQQr5tQNC7CGkO5x5nbia9pBRjOBYO0MNr2f8P+eakOqbYua3qDtHhiYqTBVnG8JpswHT+qMS9WwnMRqksTLw2/NLGU6a0Gc1rjSY7GLo0a8pz1TkhKBUlZZkX+o+u/ed+Zc2eZcZirEpAaDZ9PWMUiNajZRf8f3v4u0pYB6l7S2mRxoVieMJFjvRcLzBePf0fyDwNocFzb0PNfvToe3dzhCGzFQbDVLd/peNtw6MqCIGKftqDOWqNmqxyBgOzMn4iBKpW2jq2rDSU8kj8S8VSye8otzES3aKRQSVitM9uHT9vKAA8AA4PFOkPP41GmQggFj7VY3L0FzzZ5XwAa6Ceyni7mEg/p8Z1qC1rLuyfCNe4AQXlXnn30B7tzc27kDSSsWBWY5WWvEB6d4CZcw9LN1a/E0fymvhZoe6kx5Fxfm1g5WMUkpCVReXFMDOXReFMxKTqv8ftX+u6MpAO22fc=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
