jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: b5xcUdJp9bm8vnxSF+s0w31qa3gZ9ytBUp2qvRVlg3gfkh6YNqUoZUOkVvAM+DEj7kE1S2DQ9FBLE+/L1toKMLBdKeL8PsoSggTHs9RcnCzYL2dPGcKnX4a6jIYfZOogR7FW0MyAK1iD9gHJ6x7cfHGSPFcLePRnlpLEA5MKPNuoWZ9U7pKW3Hvtdq+2FIxC6Q7mtZzrLk6BBWROA6pr5/zW6Au6ALcxeJM4lBFF0vPUl0r1aJjsrmyNSrzR7NHoeyXnc9RizsS7uSY5hwSMLvbcRjUkmbtkBVB5tCtwd5rMIxKIDif2BsgpLiJrkdwWvUS+xmJ8dmB39q14gCpAS7UJ2JyPf83n6uNMZAvo/NtyHfb0Tz+aHcocbku+sQto2dzsVy7PqgjwqeSIK9mjdHeTKHEzB+Gjp7VdO53XYVQkKwZuy6S7g+99aDGFNQnVqp+DcWmCya+t5QqYWFOj/Nh3jDO+dPAZd1BqZdBsLzgierjIXtIYC0nW8DGb+WHacvKAvvUPTCEY06Q8KdXptoidNlMnYXGPedIzcT0EE21Ibqn+YTKhUJbJMfsK+9ttfhvFvkKsPgFF01oLu9REHSvFU4k2hAsr/Z3i2MPGPpAqGU/Xkrakjw2yZ/A7TBJw9p6sEIkjkPYhKGRRUVQJzxazp7+lRLQl4JiiUnlxIqo=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: Q6Gxq6sOR8K/7pKHo3tRjfjg0tnlNlUCTRZRLvl1P9E3M69Z2rC34U7Cv09UyAbmur4JQbT+0A3sbfSthkBw47o01T6vFE+Mrw6GG5UFX9ZyzMKSkZxh9fzbSf8EG8ySCOQWlNa6gHyEqtN+Espdnt39mCZnEt/QcoWhmytUgaw+X6esBlSHWrbOvaZrbV/kQoz3bfdUm1884OCAi0kaUeQdeIe9ciP8Sz/fl7pVPBZYwnIVcCsnq0ugEQ04TTkudsyf4IfU8O37ZRpI5TXmyJtZGJqYiiOoHPQvh1f2n3fOgFAHFO5K8qF0U7C9OBH69S2vWwrgnOp+qPUvGbYYTYOJ+VkYozXfQZHibUAz6X3CC360ImmiOzS/9IpcZQ89sfYkCRIRl12R//VvKh0Rif9nDz/wP+1j3hRoY5rUUXWa6k0PUMLV2zm4dSilubewzEQbQaOyYGgCsTf2eUxF8ZkmiaNtNkQnNpIRXWRgARXewX3NAAJYOgd5iwcRlb0BTCVHYWpo5K9khDA8W4oVAMHGI8lKAjka+4131FNy+1Xi6vZmyLR5GewyBxOgyozhpv72+C6IN730hoi6TLYnN76KQ7gF+lT2w14zra4es80dW0KV9Pgn8btXct1f1Nr7uJFE94SBWnMECde787fVko5nw//eomS4wbP16fhECDY=
        - secure: dy1Zibq7lp561/tot1DiQ9MTH0IkiNhmEtS7dTs81yeuu3Rie7pJ+PAkvnBcZw513pkKU532FDhTU+/kUFH09VOY4tDqPiISsMAacmsOofM2zJjEOxTpuMhsq070sipQl1j6rYDpoCxJHIQy1kP1BvDWwNdwxu6PFohGmK+NIkSgJc8ci22UwsztJaxOhGeEK+ora2Y8LeHdQr+ZvdK+2Mn9w2craH7/cpYVtqBe1g+no64HLrnzuga71yg2a2Gt/lSvRflNZ9lXT7LwrJkejYTxMU6OYK12hZ/VnKEwSbzmNX/efFBjP2GeAf7Ctj6AodQ5fWlmdxBuyVqohGWOJlEh7KLtLKOFGYy+1LdjXiT0Gv8aoNjfmpKdHEYHgLTVkKhckywmMSa3rwZIGkwSKsftNzzs2wMjn+TP0grIetQMRQ1f2PenwbJdImOrZFN3cHx5Bkq+EFh1ybv/bSQ36lHcfWu7DQH2Udo0n5/LVOwAql0fhF7KhiHznWskE8VZDpyUdqUgt4ArUOnIONAD3t7Z8MTsHhHqmyLxuSwZHZx8SnqpBSgCMe18EPKcXifts23ltvTf0+6NxGdSlaVEU6ul6UnSehhGewEeJQpDjoclrQWNTUQtAJgozRWGlmCAhSUO77u44jqPP7i4zYU4Jbd9Qf7llGE0xauiC+G1OrI=
        - secure: SuZRtTbTfPHH+ff5A3BRa9xMdmXU4d2wN9sur0fwFB3q+BMHjBES5R2RijdAcoXNUuFr3TXWCsmxJwHETWN6DTMQGtg5qkZ75WOs0v5l0YdrUQHPVTIS6oe6Cgr+a4Zdk7509qvl0dKk+fJntRHI1Yhnkbb4Rntm0WVhR4kYn2JWrk3pI6kIi/WU93tzyz0vvei3QUEEjqVru3YUprUYq74tAhLudLoxtgbHMHjDEnGQuFPu1G6k5s1tFjK/ZvHnVHEV3U/d8xqWCIXhRLSY6efqIwt4lyCyloeNBJVNIGVcow9NvmVZeuK/awOeInI+X7Lg7tpi9svTo5GmiH8SqlEzme5W3XtivSJNPGRx11mkG7KMteSVoLUdEwZfCbFwqlVZZ4bzAEpKETuYBPJLvSW/SMw6rnQgCkQOAMO8OcaMYrt+udpQ4M4/EmuBjvzGUpMCdHM5EMNKQZpHVWaLY2tMe1nl4kuUdMp+rUfARsuatvHEvu9FhYTQDCQll3mjUFarudDnsUOqBkMckdlzyqALbMPt0RS5ZmA4tsZCzJcn5Uwu+6nTBd4dviGDhrSebtiWJhHap2nji6Qdxplu80XAvXrT7TvewciDD6TRFFCRmXMtE+flvsOmhUvMYK3ilGQcLFknsMn5yK9gVe9TDN0T25pCR5vE8h689GT/QDM=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: b4q+bXlgVN9cOatND3VriCHFgkGw6uX3TUq39v5S30CY5RQ3g4MQ4jmo7mvkcr+XT0UD0njz+ORp+r4hvIa7Ns5PMAa3YbsQqBLWd+bTNP6uTibuAPrShxYVQHFN9ax367wSeDPEltA58jrjXLzp/V93lfm8S3qd8i3xUIowFSbKaR84LKE4McT2UiCDU4y/X/eQp7bLv9bofeOXMIjiWOrsanvP1b9FRTAOcTkgU5WIyuqYthuVzHmEU5Qw8pYanVZsuG4BWWwGB3PbgT86aruGV7OflQc+mPt1799/jFYTYgvEiJayEBkJnPDccq1nNx6+Ey9f8P/joSW7jDQnVsWcSKCdB4EkeDGrHSyooBvMkSUd7TjCtpzHBGR7bHCdGkEF2IH9M7aAB7E2ToeboJd8jb/XlmtY9RobtJ2JXKJHZD2Je2hdw0KApqFvQfUiwBC+xbrP/iMia4VDLsA1w0o61bOgLDdhZhIEtl/SJA0ChwWeiw71s3TH2wE/BWZ9DBFRKMoA8d7J71wMPFqlx9Bl9WPyqwfJ2BtzwDFt6wFfzguSomPBzZQtp5P2/18MkjsEe2+Rv5S0bv8+1nuLMlJBvk7jb9NZwQEDEyVcI+iBPT22/3eiN8cupak8Wa+sul9gz/3ilslTvW/7NhAVZmM94t2HAIhvfCN3xOk9uG0=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
