jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: UAsODVlslIpYpufg/UAOcMdbI2fQtIpip4MMNVvQKS+k0vuM4VoDGyxf9mVgaGXOpFt4fjiEIcBCq7LyfszfzuSRAW6+PcNxnH3+WSWhdMut5kIS6AWBNBYncDaTJ/KcfRL+9UEcHsOcOWKwu27cEA0C5AJWTSGud9X+m2FQFrPfJpJc1e1MuOLcdhMZI966bLJqdgckjFQIrZaPDAkrpCO+6nWpc44RfB02Su2GPHgbE6CgfdDAlz3dFTMvaeTNs0EPDxBWysRdvF09Y7bQvT9RbjkXu/hBKS5k4tcdWvQiwIFEicwgrIYiLczu2xnDALBf5ElYpkU/Fuv1c/DjZjrmGqXpeHC3eHsCQmP0gHcGutw//3wHnrVeZfOEZ34/eW5D+X4SCBF10RaQSZO1jKiI80icmFcSZdU1ECCkMNo889N660RtNUkjtF4FHGXf6MYw54xHyxXYo1ChFTq15vsxW3XRn8BVCL2SX/ignOd/pIdVKyi/FxZiZm8ZsdpqSMOPuOs7VS51zq3s5TPs6XCAM4fskzzx81C5p7jB2SZqzk7pNAkVsfrn0ueACGuu2vz+6UZdniyz/T7EtCFpnTdAR1czzOBs31wpFJaMbLyPV4y2ub33VLFWdTkOCrGg9j1BXviRtDL6PI0BQwMvXuSnYA2xVu0SxrZet9qdmhM=
    - if: branch = master AND tag IS present
      script: python scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: lXXuQD3KsX5Wre/qe9Wcc3VPk2hmwGjUXlOtnSS9BEEgLMwIsYiqL7C8elWDd3R/kbw+jHiiZoGmIyud4bPgBgnE3/DPV9lGl/pIWvuXZnypB6FmxBVCRM1gDxiNXqhZjo+KOxDrmbblhvwygfX6/22JKofXkA0yFprAsPbW39yKH9TB+mCg4GRSe4yRlYUrJZESIJbnf2v5LRxKn6v13Ut5AioocGVNHamz2wxrPgQXi/piEPAebDaURkN1kslWtxaBRPw3/GHJUxYCLlQBQjLd1MDML1Is6smIgzBFC2qf7GRW6mgeAUYGsuMxuR0rP3YNVxmadB7cDTE++yi/UaRvWXIuKpdGS6dOIJTFKhh6M/tkoLK8g2Ts8kiQzKIJM2gvbieRWEHswfmZx00R1mTHTOEkkVHdLp+76EGJWDVIQmxWRKHw1MUbAnu3GbENGNRNzb8v12NBnDfVbhoS3Hi3/JApBlzMj7V8d/ozey8OxH5/I4DW294pShvyoXqrESDxsIpc7uq7BA+zvWj0EHJtNIrNhikx4a/XffPXf4yu+g3bul4D1qbVg8qfz8ljcZvtMglSIHUNSm0rH9s0qIKRrmhyPRg3ygCTMs4+z3UzQ89z+BTGlCWvjw7MCFuFQPFYlNaOrolGS/1ic+MDp1Qxiyph5gs+98BFgeL3cTU=
        - secure: sTBQkRW77Gj6y8+WOA1RsKZo9iEdRNZHEyGlAgOxYQodjsb2FN3F7GH04kgJJYkzOlhZYpF3dG9sy/1/5A47ugOkbzmjqYqnI/AphORRiDAjcxPPeXhTQQPTjTaEQa/xLZNkVFIOT7xrkncuARiSzZySnwGModc+o3/AUZ56eQMp+STv2c8ogH6lpTFitsuAyF9saNqEOL8GCHv8AhBbdXpjJDbl93QI1LM9qTzdz3qXLWfbwDFzXJY+Z/99Rg+FE1+HWSbmSkN/kTk0udqu0Uo0DlnMHGH7PetssvqBMETWf5u3JDN+j0WylDWBEHcWnSU/sCcLP+lemmmiFCV+6BYGmLvnYgxzCdRcJ7+iC7/AcsOje0A55gjYSbY0LLE5XzBaQioho4Z2OKyQlBlD2QweOI/hi/Tebv+eeSP2cMmLYI0Brl1mtOxQzsWW5QQjLKB+Xco0nMq9HymYEbCMPaDhNMYHFWvlLhXh2AVjidfZ6NJCsBs1bSHPwAZICFKSI8y1rjj47cSn+RB0OT2M+wHMq7/+8K8WoviWq07TNZQ4D5+1Dzi90GheFQ69jIWAKHXKsEAdzha2mIWYxOcvZP9GsjZ+osttVHz/fmgCRcdoDh14edB2JkASWzIaGZaBzkktjtGDSswiV4l+PImI+uF6WxUABXgv2S07zPgvmdo=
        - secure: VheXIqEEM3UcmPepeaZ0xtGhDo8tCFkQQeuO0yf7Bl3p23dhvsT39/tDrTF1nwCBGB8ny2/RDjdkhqF+YPWC2GrDIvbYiU0pbkYcIvNENNk8QY4P5brSRvtpxuRaHgQ71DZUAue3PurTirkuEbCwYt77SGgoCUfkjhkTjdOXCNMihrxXYy4vM5qzPHgeObtNA7s83tnipKT8D64ATacnjLzViszG1xHneFBidsBy1oNi4CboefhS7GN4x5i4wdx8zXUsD2GTdaxHfkAY+6Du6CkWQrngvFbeAC2a+uNn/TF9eeS2GlHDUGHXavDccPpvd436gHfnc4ff0WhaCw8rwzHiCKXfsoXN4ScW1jZZjYtbhPKlbtApRCocpEcoa4i0saYksUQStCp08XwT5wmoLjJ7NS8YCw8+w0gEZJEIzQ8bwp6uIfPA/PjEjZmKBnVnRiPxem8xoBBAiCrhm8xjAmYV1Qs2HNGEheLl9j/cvjQLx/esXlHCz+pUfNvIdE5dVgm6z65i7/+Tax8GHDYfJe92LcdA6Inx5B7onda+3ppfA7hSrPQ0cXyuWOxB1YfBafstLwkPkZJwxAxvJPG1m848FrMibI2dUsiiNiYItauV94m9m1VNGM9wYdC9ydQZsV9arZgXw80jzQQ8j4h3inK1J6zUMC7BzHaFNcFi4KI=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: lXXuQD3KsX5Wre/qe9Wcc3VPk2hmwGjUXlOtnSS9BEEgLMwIsYiqL7C8elWDd3R/kbw+jHiiZoGmIyud4bPgBgnE3/DPV9lGl/pIWvuXZnypB6FmxBVCRM1gDxiNXqhZjo+KOxDrmbblhvwygfX6/22JKofXkA0yFprAsPbW39yKH9TB+mCg4GRSe4yRlYUrJZESIJbnf2v5LRxKn6v13Ut5AioocGVNHamz2wxrPgQXi/piEPAebDaURkN1kslWtxaBRPw3/GHJUxYCLlQBQjLd1MDML1Is6smIgzBFC2qf7GRW6mgeAUYGsuMxuR0rP3YNVxmadB7cDTE++yi/UaRvWXIuKpdGS6dOIJTFKhh6M/tkoLK8g2Ts8kiQzKIJM2gvbieRWEHswfmZx00R1mTHTOEkkVHdLp+76EGJWDVIQmxWRKHw1MUbAnu3GbENGNRNzb8v12NBnDfVbhoS3Hi3/JApBlzMj7V8d/ozey8OxH5/I4DW294pShvyoXqrESDxsIpc7uq7BA+zvWj0EHJtNIrNhikx4a/XffPXf4yu+g3bul4D1qbVg8qfz8ljcZvtMglSIHUNSm0rH9s0qIKRrmhyPRg3ygCTMs4+z3UzQ89z+BTGlCWvjw7MCFuFQPFYlNaOrolGS/1ic+MDp1Qxiyph5gs+98BFgeL3cTU=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
