jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: RKQawQedy1iZg56aY2qx2LUA2pTz+gr4qIbBBJEhFQAd/tpVEnpfd7P0GlJnLbLfeCJxwnwQbQXjHAir6I4gu+dk/s8DtxkBSX3U7NSbFuUi2tm2QR3EZO7TI728aZ0F9MwHRxuvUj79JBZdyHI7D6hpN+YpzIxrcLNP/t698ODYFG7so7f83cokp1MBdtGNtc0HNZqW0D0kBkorzlHA06biPOLuTDk/+Y/RZgKfxX1h/0ZAxtvVFldPbpYRZ9EkK+tAAkY1+P3nFzcdi1pGm3V1EJWjXXt75xHL0WCzVCPX9hy2lGtk5Bb0WzAV7Io1s7i0vPKPTb6GeEe/i/41s+4PNtonvu7WtiNspGg/JQjYJEcYJSuR6ULIvzRtij9nnwF6OtTe+Ehxc1nXSGlas+cu3hko7IdpCHfRqDFfLDR8972lj+5adkgKK+6Jb9DV/z9tzng33yVejXVdg9/0M98dJg/Jb4+8KY/X7Wo0wMEhhUm1Bkxmaa9730Bqmw2tZ3ezGMI+nn9p+g/J7kDmp6oGcaKMdnhDtrdmV5NbfHFogKGaHqKFy4LU0G4lrjcZJcInkMUY6FV/tLDooWWE1w2eAyuxk2nmRsw8BN/SpVZJ2tg959MQ82Qy7h1wONsCOKjyOGmQLVNPxhFS7UvWweUyRotosCqsI1sgU2iVICo=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: GmRDZI8VWwSV/Q3Cv2Q+udWe7jVa5tbpGxr6TdEshiwAiqQRPyk2yLjyl7a1dg5PzCsaBW7ckfMtCpUQqgEYwklEvCs55bk5qh330ot9zzu1Yh7z/0NOIMHfsDFwWkM4QbjEpOgsRZA3VwAClRBJsoDWwBYZ9ljQnAQa/Lq7SZDepHyQCSJ57yT6BkWJ+ijyupimvNXTEuJJ0HcG5IHn8ChkZ0MxmUAZe8yo7POPQsOdJW4sIa0bpq0+Eiupf3gleGEGmxb4hgqaVbkwXccM6UIcopc6DiI3Y4a83Ux0+aZRvMy11cSj0gYx2mdH2EXLOH/kipyqguorq1VJsuqng4lK94J2orivIRzPC3XrtzQ6lmjHTsV0TfZWG/itf0tgf/iYJ44KfUSICfDn0ZmvY9skccogHwosftBYre+5hMz2mW770eDGbNK38bkelo6JVxmwH+R2k+5ectXR0YkQ5Jq1iNfP5VXAGHrGoz3pfmDFN4P4Cc46cZnI9MXGqfQ7Rz3429m44M505wXzYEAW/xbL3G5Lm30EaGi/VFod/8U2GkIci9N7ZeEOP6u5wjgfD9xujuUYodrY/1XYUNxmgQDEMK7HkP+u4/rdH9TEujfRbI9vPDUhZyiC9aTh1nFHEeuFEJywydPmPLZ8uUic17cDozaaopcDuCcVUwnWfx8=
        - secure: a6nOu2LwX6d54tmmN10pdrVoz34mvjRZpSvPOFYV09V8wHu91eH+/5Op/3jYC6CDvKp/yHKz2bSiNk2X+7ngZ04g3c/ETkYEoU4ENyQZjQH2wQPDs22BZ6U3022LD+usgEMOmk3Kw1siwBOaIxvnb2CAeB2sa8i3+BA7o1qqTpp2dJl2N46k3aO7Db8kmwyCzYzgGXkwdFuOMHlgNxTTAdqMhK+HWUeWoTYtKbXPTCig10fdCqjzUvCMe+scaLpfipsf+2U7TxOo9jp3RKQyq5OVF3RoBZTdqRIzy39HZxK9r4I3XKFsrA1DkG50jS9WsoYJAZk4YGr1CxT8PgGKgcLdhxUeExw2yiGTQD9wel0WyaaGaFKJB78nLZ9z26KgE0wS4KJJ0ri22p9ZdzstwxrRex7P6mnATcsmdIT88U1FJRmgsOBheVkzDSqs7J1V9b3pSgMVpec6qwRUJ0/E0U4aw22FHxb7d9vUhKcxSIAsmKDbQhZAL79AKAT+wdYWIB5CZ96DhudlrAh58HEeY+7S5Dmy6tgspP0RgjWYfYNT3PsS9kHE1ZZmvHFjpltipJ8ZF6hRlmTxzpNkbf+q3dq/rsEIleaq6HRMTOlk2ZUqfeRPwfw7UKSuoE5HPsDgnj9MU96AQVApJvIM7/o0PisQ05BX7hJzemtdcc58lLU=
        - secure: SHD0aIGEoviCmj51IXn/jOwZ6us6JLZ99jZ5U5jGkyBEBym6B17enmPlJ56jdlxuAp3OLUFGUmxUrecuXD4T+YX39Xp8TpmFDyZ5fM+QoJRV9oaH/DX8KF3KYku8wKFCejl2PG06PFg49A04+5TUAHwR0hhpjBmROWgUDDgyI+ufgpUDv4n2KhzUEyTB1ccg3mvyK+QU76yGDkKx/+2BIJcdlnEcK5E35D4cc4rZw2YCz/2wLepdyOB/MpwHhmLxTMniaj7INR3piIleCEXgUklyP///sGJwiyrGRd5FJzQb0vX7JRsKvkoiqq6O0vYgje2MO8KA/JCI+jU2WVgrys6Kzp2YQlTrzE6Z12ZV6Rvg0aq7vPCbgiO+NfTLgTSpTZ3UtKybk+DNlcC/7J9PIipT9FXLluvLvd3p3qB+ArdlwJu35lDFDdnRExf3TvfsJ1NrqevpT6jPBMP9vXduuxc1qB5hutkET3c02wbZz5JEH9ysQN+QOA9C24wFQDNhXsCI7aIzFMS9SFBG7h79tnG4VzFW9LFpyGXihHHoGF997CLuze20WHSRv4zZlcSE0Z5z43vOwzrdNdQ5GcMwrTV36SrQZjMhHe7deLGRE1l7WoSQ4sCjYzVFCW5SNcfS4wrGj7OjUimADQAvuS+kJQzkuKZR5zfru2Nu3EL7yOE=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: EI72djtQeJBwC1EklFzQaNqRnD1j5vNcDL91SyYAm7TT6LJrqLQ4FcFq/9gh4p/RJB9uZ2jp5Rh2Ms/mKJpUNQ0wTOb1f9xBvZQtUEmTiqwD9UfjUA4G7ZsfJWhEz2AT1WewSEdyyb4FVPLk2J+5KN0cSpKxq+1sW+kzjUfxIzTzPtB5bOFEbKkUxYf98PciUSCxvDFazae0KApz5N10QZ6fm0zrtmvD58xBoOw6PNaOFeNwEQWolNNedUBWxSFLnNdVp69QbgPC/cb/jJoM3cnOfOwq4UNSqeaeoSaPvrV1OYZmkYFYyW9VDRt3WRrhENJt7d3gZD9lBVJVlhjC36qBkb6ejCdDVyHDwWl+ZcBWqxSHYnLPIniubUJggIeXvGg+7tBw9sOIrROEMnpIgEDY/1l78oeATSAMR4JWL6Sv36R1qp+iv7Gksh9Dvpc3lkVJYGg1k6CvSa+9W0IEi7u/zLaBOaiHKfPjWmgPugNtONBePWcsX7hhDjK78hA3H59WhOfCd3FeLO7d34VNwQtoRyTIW6rsSuAfF9gfDwGBNonRY6Y5Nib34UjgD/ehHZ71CXGKmhBSmIb/n/P2OqbFUP4kk1yrO8PtG9ljmbMBCQmGad8CnE8DtaVIdtDOX7ps4KlTFtoT+R2o3GdGo2yLjWPVk+FWupPX8HSRQzY=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
