jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: L6Nw2ja54vaJN5EhPg944QhUgU6Rf8UwaOkO8MCO0KdG8JChd0zijKMWOi7aeLE0YY1VMtot67WnuAyCrxJofIxVCVa2L3VjbAbdm5BFjtUNVD7hY5KHVeD7F2AGyY5lbUZhMt+7JQ0x3CgGlB4+7zs7IuVELeYjrXHGKza2JZ2np2NtUVFRTFVYNlc0jKkGsfLqV4VDntyswA8HBhgeFl2LYWOrf4H9SF0Nv3cc4VGSEit76Ze+AqQIK6pCZkMASbkEuqax7uZvCfrCQ/Q2hYkcSlR6a847goq2hGFH07Kzteg19XURGcxan/+Iz8cK3x+TZFX+dA8jEZ5yMV89bTs8UgGmBocm3LgnfNPOLud15n2WtdwIR7BlUVgSkkYCIlv+ZZFSNbyBXERDI4c1EgnsmQ117uvb9OzSSDmlGvNXFqH7u0c+N3d9l32aDyRYgr4Ot0QOG/FHOFIAQE2Rr8pC9UDrPpHwQ3x/Nu3hhHkGx4QlYUZ2Oxbec+e7hTEzaSa5UoOMGpvmE9CLee8Rf+TLMJ3DfzpPNSYP4Ub5WCPNHbTZmedIuinE7OfLM9RivthElckNB7XDbQHCoE8GJNe+CDSGAU/bHlqTAV5YYCEKYto6OYMtth0CBoc4JcE7wTQzl5iJsddXeVde4YFgG7rzac1swxXg3u2ME08N8zc=
    - if: tag IS present
      script: python scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: QqCr/CkS3nqB4wf9280XQE1KyHKd8kV3SaIBqqLeaBeS2ZpSvbIHlOZ5Bp11zCqNEZhlu6I4Ohlqrk/M4sLwurfbP49WtkAy2PeZRolCQ1AJs8VEwYBVQI/fs2C+3ElsNo41zj0wym0/nwEQSV/Ss3ptK6aU05UKor9nVibxJgBmAcNBpdrR2LjZTUcXUpMZLRuC245Er2kvn+OZ5Df04j1z0Il8OCoLTZ1yVVOimiqrXJ+oR9cZroeIZb8o1A716WizX+qnJwSr7AlO7vdHpcf4xdBIL7FlboaAa85yNFJbuw6SQH71/f57uQBZX7SCmFWstu2600FzAR8SEf631dUlHUucpWZEIMf0R/dsmX1PQLtsalW1Bh0npecYX5491m7KIihSih8XDUZgmzRrG/hRPWCWcl84EZNyNQLYOV6Ug2N5WcXdRIZ/n3t7Rq16abT6MeqyyxPy9iAgjyuEJ2PUPuG4acSGwqVvroJrdKETSYiVB17WaQy4VCi2GOcAF+tsbMUVb9/sIBA33HiLEOGWKmhF5vbRXz/OTMriYH4KY0DYysedz0r+L/EQo44a12H/3cB3m07xAhdxBv8ZqieHc0T1Unlhse0k+oGSYNqvFnzjDXdekn/azuFcLB+ELrfgXW4dwYLRR1d9y/+1PlQYf8AfaFG6kwM3QgXaUrA=
        - secure: uVb5KHBURnf2l4jw3S86bW/dVa1nC7LGKXMtCl51GLCOKA7Esy4QbDjDtyE7KJm9UWIWFG9OGmJFFfatjqEqaUqXoCv1pXUXtu9wLPrHGbRG00FnJlFjJVNvG+OL6vbh7DFcxXIZlDxlH1MZzaDNh6PQYckLg9qzWLozNORUyKkTYv6IGgxYdaT4dxSmvugs1mS6q/QksAfpEyqbvl8pCa995/O4O3r7NKcNTjYyed1JEomHz7iVHCAf+kAqWvMmNw1t7GvlaEALyzezMyVda8Y/2zP8svxrXjumTguKW9kERLHL8DVZfIJK5nj1gYuybOmF+lA0P1LzzJTne3+uf5APImPCKnKQ3nB8AZEqwU+UOLx0UESKEpBiqQwwwW/x49fyHQr/wISetCev67HPoxV/5LMxltpVyo0HR857qhidLDjNE2daxUABAadL7hX/4ZL5PLFOB1w3UsMtggFsRwyNAfYAhytFLeUIY8dWNUKbZsemeiOjr1LFYKwRpSSvie6US5aIvR2z3wNRYnPCrU6Bfc+xPgJgzF+5aI6u73DbQdoKjgt7y/lkTCfTy5bfGTg6vudAN/8DSwRAbuEfhPR72jjWz4WUR0L2wE+JxOBp0IWHmrG8f/pjB5CV/zSPXogCxWq1DtqJsnXkphDhV+6HkmBzfFguBMaXdEoSyEw=
        - secure: voo7/A9cyGu+2cV+ZNA6Ig86qiZOC1n7DDgRdQVeqz3hiPtEXAndoSjuNXC8sQWb/iqab5Ncg7HiPAOS4FZlvf9XiiKjU8U/IemTITmjlWcTI7M2VC34ws3sqMow/MgfkKk0DT6au6hPTvnSXvUEmOMOXbTUDdlHOCvBbWzXm6xAmKcfxxCzLdNqImpqP6mnpDsL1AtEF7WG9/TZAFq25cYf+lH6R4onZFOl1e+r1taz42sGlIh1x1rSI6jn7EPgh4ftlz7pPxP5tjqmb/wzLBBtiBS7Wuz3SUIRa1KLTnWyw/SL2CN/Wf1avRzZm5eUTotkuif4/1LUi99qUFsuuA+kAK/c+3NS3/lUYMunhDmPB2Pg88TVkOeXIVi8mK93f3VAuQ9GszoVLOrzMhfkgfhRyPvHidw8gBesoo/VE6VHeJKjOJNdsgFPzuWYcf8WQrwp9UU1C4OZ/iy/V89TLLVtVKiP3ozdomCQC+IuMH2hdBs7Pxkx4tklzZK8O80XUjlqOawZc2RCYBJZ7w3ECHuKzCS5gXDWLH+P6KdzBvZphMLMoR8lXFGajEu4gWX2Z2lpEyiJnvYXJ6rJpIE6PrSX13TIsRUW1YG9OsLX52TC2w1rWkydNoSNeYiNfgaeg4qRDtANcJpkRzJ+EuR9pTc5iuJ9DTOqEaQinAUjN0M=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: QqCr/CkS3nqB4wf9280XQE1KyHKd8kV3SaIBqqLeaBeS2ZpSvbIHlOZ5Bp11zCqNEZhlu6I4Ohlqrk/M4sLwurfbP49WtkAy2PeZRolCQ1AJs8VEwYBVQI/fs2C+3ElsNo41zj0wym0/nwEQSV/Ss3ptK6aU05UKor9nVibxJgBmAcNBpdrR2LjZTUcXUpMZLRuC245Er2kvn+OZ5Df04j1z0Il8OCoLTZ1yVVOimiqrXJ+oR9cZroeIZb8o1A716WizX+qnJwSr7AlO7vdHpcf4xdBIL7FlboaAa85yNFJbuw6SQH71/f57uQBZX7SCmFWstu2600FzAR8SEf631dUlHUucpWZEIMf0R/dsmX1PQLtsalW1Bh0npecYX5491m7KIihSih8XDUZgmzRrG/hRPWCWcl84EZNyNQLYOV6Ug2N5WcXdRIZ/n3t7Rq16abT6MeqyyxPy9iAgjyuEJ2PUPuG4acSGwqVvroJrdKETSYiVB17WaQy4VCi2GOcAF+tsbMUVb9/sIBA33HiLEOGWKmhF5vbRXz/OTMriYH4KY0DYysedz0r+L/EQo44a12H/3cB3m07xAhdxBv8ZqieHc0T1Unlhse0k+oGSYNqvFnzjDXdekn/azuFcLB+ELrfgXW4dwYLRR1d9y/+1PlQYf8AfaFG6kwM3QgXaUrA=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
