jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: gcmkbEcip09poXF3+hDVrI23ZmqklC26ZRq2jW4krXn1A+7aeuS8Nf7E2t2hiSVNp9QQi6DmH9upzqzKuIEZYPxxruyzY32qYa/KdwFsXoE8OtTv6hoJaM9a11mT1E3U1eoi0e7ky+oL4XyTUHr4kCD+J+prUqFR7Jb/vKz5BfpxueY/dJJ6y+kgFdKfs3s2UouhCfhMXnvSYISuvQHXxFcdlSoKjlRGLFczvwZI7xhHVK3186lM4gIvwIl3Het33+ZVBtcXgsEhoVlBayVV74Bdv+6lTFZgJ4tObojRgbOuvtsynfejHpmAS3NAUESlpQ9fOdWEPMuzV5ZMwDgHz99fSGgHQos5OgD2uDfze22eONYMQxX9GWy+YcAo/pSLPwo7AFQh4D/aeU0cAkycXEcfwRWvQ2CcmYaDa1znd2YM/Wlxib/f6PiUZnAEy3h9XXG35s27FxGZnRk1Gf9rgCYPWoLaMWsCsIOS/QsbCKCK5He/JBYD0BHREJmZ4SW/Q/LZcxpKwoh4LtidQ6KCm/NFrGh6LMNLToCl6t5jSlgzaDm/HWsOm/BC+CLirsVuo4zQbh6xOOj52meD3nq3zJT2AdVDYPZQuzJ56fDdVn4+WrZQHLLaC29STntVgO/VA9hX4GkDeHhpFKMhugPBbY33U9t9KTmf9YQIBZUdlF0=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: wz7TmlCIw8zYyBvRznM2f3FbN5WqZ2H8OlyAKep9sAOLC8L4gLoCZq4CcaFXp/OQ7L443MyiCDOmUESs61vN6uT8P+zq9MqS1VgLx4noojbXmIWVr972BKmTN0cMWk1/tWYSdYLFHvphw5F6KRywvIyUM0dxmwpk2TOQf9JUFFPd29WI6Glu4MSueVxk4xasVbUJ0rdUclQp1kVczdbeZ3//CEKlnSdS5cMboqSsyNIMx2KOVZT/slJ1TtzeN53qt+4nQUyVqeGc6UwhNG4IEn/nYoemV37hKRfmbUsruAVaslAXcXLybBxzHtA62ncDDdXNJLdNSur2ainZMwgQdhAlkTFmjKvTHgZSaWkImARWgLd8KP8yfy4qYQb93R7cyfAPcCYJLdK0cdwj4FFXNBbkdFdnZQs3mV3lgdD785jywdaZzh1nxStar2ZVqYfCeVd0FUZgaCnEdkcDsC3BLJw2hRgBdCjBnqi48NIU1Z1KF0l8+SsgN4NcGTW/afanmu9ihvAPX1icby/u1iEx6y2fu9X1h/Z+tqOY84gJseTM5hWCag44vMwu9Omh4DexIrHhZa385CIVQrXhs5my3lIhxbrrt+zSebtCHQbwkGCCuRbsIqEmR1rAdCk8rxytx3zAtvEeP9jmS97CT53DU+8tv92pZBMqLxh+9ZmiRzM=
        - secure: VS4r5KtAWVVdyLEuIoftIrPLWJC2oKgcc2u3cUrpxnFJ1lc7BuOkNs1zKtGADYuSi3P5YP/DWLeD6IZ2sx3qbDx9nP7YGRCAUjCGgDtU6wr6GDEMMVo9+cEaU05MphYijofC8Im45m65yAG2oVOQeNH/HOLkAzvzWFwSbaFf5eVC6KApj1ne5EQkISwHImjoq+dO6uV9e0fMeAF49Dbsv0xOQ0FwY1gVp+bmrRGqwcO4nYB+yEGvcoC/zXLvnkeiQI9mEoWfkYWWPMCL7O6bj3yghwLs6vDAUuQ6tcA9kpcNigriRF7t5plCTwVhP1kdt1LMOIeLR+omwGLCpSIrBTqxlyObiX96C3Df25IYbno53dKsXFt8cg7TiGYmdqvm2/oez5BM0V/7cbAw/Jw09XFKwuOJXfRwQyoGWCknxKArRwuNY+lny05HPm2uM23iKCWtle/sYBml+WbXUVQYgEhSMVtZ5Eo2/FjJkydkUrA1mkqL0N9t7FNHa8Hjsu7K/weO8XQWtnquKZwovYsBnMhFASARImCbE6VmHYn6ic9CaeQO2J2uu6z4HJyV5LuQDhs1tK9EALxP728i+/6fPYEzzGKamcqPXHJ3aXFBZWkWqxE4Hta+Fpvwc6EPvdZckGn7SVfjF9MMVk6piA7HZ70Ad6zx6S5/cG97VDVF73o=
        - secure: lIeSkPljuf2WSPO65VALnZ7cAi8UpsZW7EJDEOw9PEERj9hIxt07GRXhrjBiJ11sS7bcBi5xuZQ4gA8vrV3AF9lcqgcPt0AUBG7p/zMCEfbE/grN8JC+dUKzkIm2Rlkymo85DjmgEBlOgQxKoTBWilFnbh6nNQpiqNE6zfT6Z8sxcxTtHcF3DInCxWcFSxRvFwlZgEPdAfVARgjc8FLfwZ9Vw0bUSGDhs6/b9427/0rM+ZkC4KCMnWLMb8FppizVbqNWhgmglWnWkObfufIUH9OsCRe2sG0N6/AAbXeAsj/zqAgsH7wa4Lieta3l7h59wrtc27PvUm2bz98lKoJmfr12uapAlt8QENNyEaP+rH8hlHLe4jvtLFWoFMRn/bOXsfbfJ5K/0AlH2Gkv14DT1BgPpjTdEU74QSQL35bqaHzHCJwx0UIYq9+o9vTLWzDZTnmQKHuu/R0Yz6C8mc7eyKcqEiiQOHYisMRjw5NI7t+Vv1osSSYHWRfHprJdoVRtgCx/G+uOdX500hnpqBcFR8Gaz1EcgXmWoRnOVf5bxH5SvxxGbOW2qGiUO4zrV/VeFhptVqLgurqlhHWZ+K55dzTrl+pGp5E59izk5lWpTfaUJUbDRlxqWtvmYYJe3y31NSeciUpHx/VPqmNzPjulTRfrTY/APVWwzFGrkHAN56E=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: WWw8jx9h6CG22z/2aOhcjHHr4otVUCPoUUZo9S9lDwKwGtEfhZbqhEP/ufyyXEQvOfHpWFbGM9yHbwLcjqjzCYUoX02TsAtFh/Q/Thc7dHVHoTTFXGjiL+ReX7lKY+7SHjJqWenq4aO9CdEeQmTeJ15DE81fzvziTXyExnuYTUNvUvKWBN8NO61XsRwT4U2PHeNEwsMo6Cl4E6f7z/K2yVFn5aTDlBcI/sI+3nhQ0zzbKwYShSWNmoxyMUcak3JG9tuQUMePVsHe3pL0nlSA4Q2MlbOVvAAm0/gsSOrT99xSBAQwkTBQr8buKHNKqejej+IVzqSJa0xxwOPm7aqnxnJ1WTQ6GicVC8xk9/x7mdJKoNskMQQPGpH/+6gGSb5OTRJ4++rQPxvgh/+x4g4EU6RPzeWH8+IC24q8h10e3DLac/gZiZ9MQeFhFaf6eSlgDvJW1+jvoFKa2xW1b+UqHKQinQvHU5SfLIKq4+fig2VO9jCVMXHVIogh88NlJdEzTVdvHCeDVBWRFye9Ct0jnfoiu3TNpdtxqK/vz/I2zeTw9kskWd1pid41XhwMsOzODD5Jk2xPU1h++UmFSQVf+JYkKdvJkQysSYpA5CBsqqgfUALJyJiKUoDnhKM8YT9Dhzp/d3tgBc8eK75KE0Or68Cm21+uDR/HHUM+lJU8Q6s=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always