jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        secure: pDeRloiV61099HB8TS8gJvCg1Wat4WMOSdcZldPLG5NogO1WRPi/oeUF8bqj3Gr6plV+r5JNs/cIxIMT7AQGShTwxeFYnOsSfUhyH4+NEk0SoJD77dhkyY/ohDZLwQFPFiI4O9/vVew04Jzuy+ZEysbeRmhXL4+bRhG8zJd1voIS7VGg8SDz5JCJZl21UwNOHTxyRSrVm9Hc6p1HoIxCLCWFv2emcAWNQ7xvg05RvH3fSp8uN5JV89Lqbd+x0S/V9ZWw9N98h1GqDSsnxae+WbaCuuKKno6bB9chRVT0sWFis0ECOnPbkwDY3n0TsRZgF6bo+Zi/KXO9UdnLoKU5Jp+GNkzJ9VV30b35KSXPY9fDUFJu6cYKumpebT6hAQtNTrWe1ukf3OD0QfTiJW6llrvvuQcbYhS+F36qmYz0fWQ8tWXaXBrMevP1ablhAn9yEn3PmNCcBTgNyqlfTNzUv+Y1N9XtVCLqyHHBs9XS7xmUhSs5G1/r8alMHZwy/72tpWEa+ghOYmE0kVcR9lIKJmjOElErlMA5sDoCfKoYJpo1WPn/S8+dLiMsEYhGAMtXTVcDg1d6qLFns/dAE1ErE/cxy4saGyl5wtKbSsJ2+hW8W1nro+pMvGmib40x2Io7qf0w01R44z+YoqdvmSASQlT8dAHmCtXbsPeYnk2IfgY=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: fTxYi+g7KKlH8Hhs+r+A7FVoj00J1N2IawIZZNB2L6MSB2/puTL3QKOVF5IprvwKcc2lhAe3dPMinhDYgoBY0AeibaEb4GFf7pGJhnN03sdxTBWMBswePf5eU4dexdpdAMldsqffMDbd7Uo22+j0/k0RhJhX7nTvu4GbUFtv4Gh0yh2nw5dDcD3y4ZLRk1SOAK8xErBZO8x30PNPZze+pjIyVcxfkOE1x2P/TfkY1bkWLDbts5bV4txb0Ycu14uS7lWE7OJvxOltl7fBVLnoCrD36fEtdlQes/ZtRqBQJAbDEXtjCHiJDIm83DY2Oh+hrYKrtIFllfYUlNn+gZM9Z3AWtv6zKYKR18XtK+TqI+NUJrAjsgECgy+RmrP2n2DDnYEFePI3YAAet5ssFv0RkE/+7eJpHZFr8mAopyWFhuxUPnnYHVwwTDMk7XFIGx6DCvjH/NDBgFpEXTfZlJ8E0xscPcUIsHr5B6k6FEZa4Dcyoae6OJ2lYVpHu+MPwA2ohGyaxF02HwLRD2ZGfczWEUTYsbexcV91+GyW/SuJHSAUE78fNu8P/WzX5LwBlmcvczTKwpYj52co5K2r6embQ2WcH0qt2GqBfkQFOl2eP00AgIjyJ9MXJD9Ai9YBbU1585jI6MZ0RYt4HZQsujQhHVSgTf1sy5wEDbhPUgiZ12o=