jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: OaiXZKCTU+WgUxqYEY+I7Gb1J2UEbCZCUniCVhyn6JhQNrNQEvnuJm8Kwhzyj0bC/Ww6rxD/nB6srY+waBuIhwaq83qcArL6ERwrc6Vg2tE7TPTpIctVmQSZZGDLiGPn+9C2sc+EKPPR7G00eAxW+vWkD9z2HEcKaArovFJdanwiLog+0iWGY7hTmHpJlHrjpJbnL9TIh6uEZbgzqIGVOMPpwvG1Ww7ZYQ5H8J2eDjeeabNn+9T1vLIT5P6/L3RTvOCAnoJRv7ELmwGoBQbSfn+GCYrPvbfGcGe22lMlwia03v7nKIZ/3KOWt6wL4AtPWZ06ZIJPeXs1Eweo5ghVNCmIV8xaJ9x3uKnY1vFL5f0Ar5fN9xDrsTkIv6W7SbK48C4G1BpIknFG4P17n/RhaCUQvDVskQ36xBexJ72fWJekLvAcIalFvsyTIYyeITm1jycwgIyHEPXZaqXHqU2Guld6cSJqJWIHCchDz1bxvnTAxxAvZYSRfDr/z6Htc5RNfoXbW4QuiWXZPs2BZpre0Mxpp5t7iDsZoUpNoaeOg3TNvjnckWkg4oOsVmHj6aJDRacPzbUZwR2wpwuhlPGo24CW8wC4We2d/FWsT7BU9rfZU/FCBSHm5QV0hkdJNG9gLEeo2LN5F24GS0re66gUXdcozYM481ueq3PzveeQ3vo=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python scripts/build_documentation.py

notifications:
  on_success: always
  on_failure: always
  email: false
  slack:
    secure: fTxYi+g7KKlH8Hhs+r+A7FVoj00J1N2IawIZZNB2L6MSB2/puTL3QKOVF5IprvwKcc2lhAe3dPMinhDYgoBY0AeibaEb4GFf7pGJhnN03sdxTBWMBswePf5eU4dexdpdAMldsqffMDbd7Uo22+j0/k0RhJhX7nTvu4GbUFtv4Gh0yh2nw5dDcD3y4ZLRk1SOAK8xErBZO8x30PNPZze+pjIyVcxfkOE1x2P/TfkY1bkWLDbts5bV4txb0Ycu14uS7lWE7OJvxOltl7fBVLnoCrD36fEtdlQes/ZtRqBQJAbDEXtjCHiJDIm83DY2Oh+hrYKrtIFllfYUlNn+gZM9Z3AWtv6zKYKR18XtK+TqI+NUJrAjsgECgy+RmrP2n2DDnYEFePI3YAAet5ssFv0RkE/+7eJpHZFr8mAopyWFhuxUPnnYHVwwTDMk7XFIGx6DCvjH/NDBgFpEXTfZlJ8E0xscPcUIsHr5B6k6FEZa4Dcyoae6OJ2lYVpHu+MPwA2ohGyaxF02HwLRD2ZGfczWEUTYsbexcV91+GyW/SuJHSAUE78fNu8P/WzX5LwBlmcvczTKwpYj52co5K2r6embQ2WcH0qt2GqBfkQFOl2eP00AgIjyJ9MXJD9Ai9YBbU1585jI6MZ0RYt4HZQsujQhHVSgTf1sy5wEDbhPUgiZ12o=