jobs:
  include:
    - stage: Test
      os: osx
      language: sh
      python: "3.6"
      name: "Mac OS - Python 3.6"
      addons:
        homebrew:
          packages:
            - python3
      before_install:
        - python3 -m pip install --upgrade pip wheel virtualenv
        - virtualenv venv -p python3
        - source venv/bin/activate
        - python --version
    - os: osx
      language: sh
      python: "2.7"
      name: "Mac OS - Python 2.7"
      before_install:
        - python -m pip install virtualenv
        - virtualenv venv -p python2
        - source venv/bin/activate
        - python --version
    - os: windows
      language: sh
      python: "3.6"
      name: "Windows - Python 3.6"
      before_install:
        - choco install python3 --version 3.6.5
        - export PATH="/c/Python36:/c/Python36/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel virtualenv
        - python --version
    - os: windows
      language: sh
      python: "2.7"
      name: "Windows - Python 2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
        - python --version
    - os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Linux - Python 3.6"
    - os: linux
      dist: xenial
      python: "2.7"
      name: "Linux - Python 2.7"
      language: python

    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: python .multipackage/scripts/build_documentation.py
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Documentation to Github Pages"
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          committer-from-gh: true
          keep-history: true
          local-dir: built_docs
      env:
        - secure: czHphW/BwkohZJQwHAtFyefspJ8ocqX2BgxZMGpQ2a/22KlaJsCum7DQ9VGj5BVwRRNkznribd6FlM+q1xb97dhkA5va/oC0fyp3ZW0/FKDoTIEz4I7Esf/B5DbKXXTfbtPqYwN9bJPBdWJi8CbxIJAhWxkNg0OYAzmcyVysWlXS39mwOT5xkqCgcNoWsJw+uceJIcnHV8X80nogAP3v93JtoP6bUDtKH9hCmY/GOt4zQjpOV4NZG4C/3WdFKQ56MG+oA/9R7DqT/aB/R7MofF8ponuY7ER66VoFqJrh5auPSo8ZdJCA1V9l5v+TuscbKfF6FOOyBHJkWlBEd5PUYkjNZkK0EsgCfea355H29nTH6frZ/GV3Vlek4XCqK1S+cIsYnqFLtC/FjXa7x5n6K7fiPcJQPKZDNq3g/BUsDS7l5VNWc5j7QDd5LWtArXsTQC31RiPckJWMjTnSPM9HmqbgpIS+Toy6H5FrSiTfhHss8q2hLXxfmvNmg2mC4ifYJfLgNCN8AgqFj/miyTBMPJ9BCRRtCqHoAAZhcy06zEerDSiRVxnMXLQ44RHSG6JF3xa+wDS3Mnl9cYCEX0lbQ5JKl/cY8qpszPp8necif2Dt0JB0UdtIusfS8mM0AkRyWzN/Pn32WuDWoLw+r0cIQ40hUAihiT0sbdPciY9bfIg=
    - stage: "Deploy"
      if: tag IS present
      script: python .multipackage/scripts/release_by_name.py $TRAVIS_TAG
      os: linux
      dist: xenial
      python: "3.6"
      language: python
      name: "Release to PyPI Index"
      env:
        - secure: S6UmD1wdvU699tNu23HAT7dwRlfQC/rePve8I5UxX9BsFjAmRl7SWuIO9OpGmgGc7X5CzNVVnJqh2B97Umb24Az4L7qbWH+BTRdyS8zVD88mJDu9inYnewZ7/RYr/VVr2+EGH35GvIPhwHZ2n3Qd/pPNHwpzC2LPfLwgpfOATxmkl4n6krMuk1SBphisal+gzs+SmjpZ13b2Lib8lDi2wXxs0nL8FkBjNVLRcV6rBu7wdwC+yMds5wIR3wTKHoosw13PmW8WvI/KSfl7hPiElWU40s4mucaGlktVSm9556aQpF7xvPCOXeccGrXWRtKaPQE6WxrNDD3f7j5dsS/yk+ipc6Gdn6ajaT7AITvtYq0z4+e69Bvt0ymbiEVUt7jTGuIT2CVpQSKJKyHZd+DUqMYGwsxA31Bkd6CO9/zJ7b2HcmWd4rWmowM9qlwxHh9r6TN+x8lGRVEmCxvm1xkKeuZNxKKERBgO6Fma8ui3fiIx/j6XbvZmpxhfSFYTS6zxp0cxvZcGHnLU5/8BTXnCBcbvZFxQyS7qWhAzw+qBz255w+DU7jBUOptrA5B17GsETZqUUWaDjVcPcANLXshJKOiOG551pdXOQ2cv7aQVHgsZ+YRscY3VMOHoYeRpiASHBiYgD5Vxtic8+gMQ2j/y2zn9Dmy5S/5qt18auaRQxJY=
        - secure: Q8olKJES9nj2C+EG9zMmO+awObA2iTvfcDOfcySxUOA6IOGJKcZ1LfxZx3Eub8LId8QVynGfKxZdVGFkCxlEAIHmFmTHdFWLx086mVzvpQp/ZXJPagdsQxAhB1DqGJ/zlcrVHKOcF2Kn/wwOrKq/FwqBEmyoO5gA6BCIDY59NRIsBvpuv1/cqkP2jz9M1m3+Pbou4I3BX5x8Icd+58jgeMIIqc+u029AGfvEBIHPYskRFsUXu3c8rF26ufqzdd2futcvGACtOTDIElwr9H5DWmLbrlL+iwym4J8sJvFvQi88ReBd9ZEDr2jAUJXRsdayTUbzsOuQynS0xqDsSSsrw3NjmiIHUJOaen+HsEsUtyxkpTw3pqz3vaZMuaB3dMGqXYoBrCyBgA113NmUzy2ZprAHS3jrfapVybhX7U+Wa2VDv/YmnzXNEetd8YZqGlPHNt2phGibyIorpy1/SfLxrrOugRlm6ejzvU2808GCfCAuApoy+limiCRa9jLYfSCSCrcFIlIWrdaaz19vXbTjQFPNgQk36ug8rD7vhwDQzXKmqoD5daZeaXE1wi7afVbWH1xSdDdLlHBDBzg4Cng6DUW1wzZDhrCtm+2cdl/YOqz7tkfdIbzQV78Dtm/SJP8QyXG4mcu6SP7IvgeJQLtKfvju7rpUAMXa7mUnRBjLnrs=
        - secure: u2Xk6OSDdr81I97JxDOV4sRQlXwdKpmOOKvH8lG8mam8xOnXb+uJGxHwZVA1We67f+/c72aRZ7FeSDAHl+Xa/7ukOSY4JZ+n8b2aSGEiErIKnQcleLS9Zb41HbJxeXJzOJoLVniNIWzFCgoCeyD+Fl150sd8GeL/h24jeo5AEB4VRW5RQ5NwJ4MgkwbufKxnWF/fGnczC5wopZFPlz2Re2U/zX8mSUmoOaa3XKC6RW0ktaa9Cz2Ex5VcSlDaLlO1udGKfuFuxKbRIh2+4bc0EhsHJ08lp7I7Gmm9jmnVh59xhIVz/xOhoXSzm/nr/mqlvSVJJYbzjmWRdsOEIoWcB9Tm4DVGLjaJPqgkJHzLtYbYTAGJeJ2MYTMNLn+tfLFNNPcLEliKUoMIqVOlvvJGcDAwsE3rIvq/XSIxUFyCwk+Xlk5S5stJpIXr0Q+pbKbqHZpAV73XusiDoXbYMtgJLvgly1Ys1J78EFxrBygOQJxYUtQ+eHpipHBEdotaTUFNnpdCP59VRBPpDGSiLCIpbZTMpmd6UILojGpwJe5u1FsNgE9HbqZNiMB1e5+4b+owijBNgBBGGAOtfGN54Y1khYup/QstG3v51ur17F/uGrtt+o/Yx4EzGFCjgWYLN9NK7u9PE+gqlxL+XSEKzXin20wb+JoTkTH+ZTnMWPD74TM=

install:
- pip install -r requirements_build.txt -r requirements_doc.txt
- pip install ./

script:
- cd ./ && pwd && pytest test
- python .multipackage/scripts/build_documentation.py

notifications:
  email: false
  slack:
    rooms:
    - secure: AMz4MPDiTyk3ucWkmUtTvPVM1M49NLeybO6Slbo7KhJzCIZ/BDGQWLw/ORg8KZcrZ7DvlyjDV9iIMLGPW4TPpRX5rSIVO6vLCMAdim0RT49TRE5tgSwiR7gFHcRMQsLWjY5BVO1kO4e62kEIoIyiisjl2qaSV40FvEqLBh2VUX0VIc/mMaU9bnHOFILxkEoToromMy68F05/5FU31zOJZXYg9iBp+YIDpAsQB0Cl0XjeaXYQVQ2GkVLR67yYTUPnqrBH/vnQkFpaxo83IZ48qu/hHWEkuvDvS+bQxxyRdhlwBC+xXv4PZg/xoYXOGl2zzbMv3EoglQRp+y+Oj9hRWRCV6g7ZGtA6d2mBAJZJI2yXyjtbts8aH8BtdfGMnuNidCXTh0myWl5Nh4BW6njt4WPS0PJYvQRswEPdy3rl68tuRsilSOJaaiQrOhD3kMWC82gu8ktA9i4pF2ZQy0y4aJ0AJEs0eGhqeo/5e+QV98YmMZP+8aF/AF319IipiEF7a/PdPMx3Fs87pq61yxNnuYn72iVxIuh/fFoRgjYJuExTnxIHcDfBQOM20Ygzs1UcDVFD4NXacfVASeH5L3Zun5zPbKIGY1hQDzKqyO4xj6bX9NFBfhGsPCiaaveRV1YwQ+6hrGPbj23fkAbfOx4k+XKxPemTwnOct6K5fYnGeFY=
    template:
    - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} in PR <%{pull_request_url}|#%{pull_request_number}> by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
